package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;

public class CardinfoKey extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.cardcode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String cardcode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.pId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String pid;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.cardcode
     *
     * @return the value of cardinfo.cardcode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.cardcode
     *
     * @param cardcode the value for cardinfo.cardcode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.pId
     *
     * @return the value of cardinfo.pId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.pId
     *
     * @param pid the value for cardinfo.pId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }
}