package com.pinelet.utp.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CardinfoExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public CardinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected CardinfoExample(CardinfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCardcodeIsNull() {
            addCriterion("cardcode is null");
            return this;
        }

        public Criteria andCardcodeIsNotNull() {
            addCriterion("cardcode is not null");
            return this;
        }

        public Criteria andCardcodeEqualTo(String value) {
            addCriterion("cardcode =", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotEqualTo(String value) {
            addCriterion("cardcode <>", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeGreaterThan(String value) {
            addCriterion("cardcode >", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeGreaterThanOrEqualTo(String value) {
            addCriterion("cardcode >=", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLessThan(String value) {
            addCriterion("cardcode <", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLessThanOrEqualTo(String value) {
            addCriterion("cardcode <=", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLike(String value) {
            addCriterion("cardcode like", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotLike(String value) {
            addCriterion("cardcode not like", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeIn(List<String> values) {
            addCriterion("cardcode in", values, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotIn(List<String> values) {
            addCriterion("cardcode not in", values, "cardcode");
            return this;
        }

        public Criteria andCardcodeBetween(String value1, String value2) {
            addCriterion("cardcode between", value1, value2, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotBetween(String value1, String value2) {
            addCriterion("cardcode not between", value1, value2, "cardcode");
            return this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pId is null");
            return this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pId is not null");
            return this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pId =", value, "pid");
            return this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pId <>", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pId >", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pId >=", value, "pid");
            return this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pId <", value, "pid");
            return this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pId <=", value, "pid");
            return this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pId like", value, "pid");
            return this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pId not like", value, "pid");
            return this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pId in", values, "pid");
            return this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pId not in", values, "pid");
            return this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pId between", value1, value2, "pid");
            return this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pId not between", value1, value2, "pid");
            return this;
        }

        public Criteria andCardnameIsNull() {
            addCriterion("cardname is null");
            return this;
        }

        public Criteria andCardnameIsNotNull() {
            addCriterion("cardname is not null");
            return this;
        }

        public Criteria andCardnameEqualTo(String value) {
            addCriterion("cardname =", value, "cardname");
            return this;
        }

        public Criteria andCardnameNotEqualTo(String value) {
            addCriterion("cardname <>", value, "cardname");
            return this;
        }

        public Criteria andCardnameGreaterThan(String value) {
            addCriterion("cardname >", value, "cardname");
            return this;
        }

        public Criteria andCardnameGreaterThanOrEqualTo(String value) {
            addCriterion("cardname >=", value, "cardname");
            return this;
        }

        public Criteria andCardnameLessThan(String value) {
            addCriterion("cardname <", value, "cardname");
            return this;
        }

        public Criteria andCardnameLessThanOrEqualTo(String value) {
            addCriterion("cardname <=", value, "cardname");
            return this;
        }

        public Criteria andCardnameLike(String value) {
            addCriterion("cardname like", value, "cardname");
            return this;
        }

        public Criteria andCardnameNotLike(String value) {
            addCriterion("cardname not like", value, "cardname");
            return this;
        }

        public Criteria andCardnameIn(List<String> values) {
            addCriterion("cardname in", values, "cardname");
            return this;
        }

        public Criteria andCardnameNotIn(List<String> values) {
            addCriterion("cardname not in", values, "cardname");
            return this;
        }

        public Criteria andCardnameBetween(String value1, String value2) {
            addCriterion("cardname between", value1, value2, "cardname");
            return this;
        }

        public Criteria andCardnameNotBetween(String value1, String value2) {
            addCriterion("cardname not between", value1, value2, "cardname");
            return this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("balance =", value, "balance");
            return this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("balance <>", value, "balance");
            return this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("balance >", value, "balance");
            return this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balance >=", value, "balance");
            return this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("balance <", value, "balance");
            return this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balance <=", value, "balance");
            return this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("balance in", values, "balance");
            return this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("balance not in", values, "balance");
            return this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance between", value1, value2, "balance");
            return this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return this;
        }

        public Criteria andApplydateIsNull() {
            addCriterion("applydate is null");
            return this;
        }

        public Criteria andApplydateIsNotNull() {
            addCriterion("applydate is not null");
            return this;
        }

        public Criteria andApplydateEqualTo(String value) {
            addCriterion("applydate =", value, "applydate");
            return this;
        }

        public Criteria andApplydateNotEqualTo(String value) {
            addCriterion("applydate <>", value, "applydate");
            return this;
        }

        public Criteria andApplydateGreaterThan(String value) {
            addCriterion("applydate >", value, "applydate");
            return this;
        }

        public Criteria andApplydateGreaterThanOrEqualTo(String value) {
            addCriterion("applydate >=", value, "applydate");
            return this;
        }

        public Criteria andApplydateLessThan(String value) {
            addCriterion("applydate <", value, "applydate");
            return this;
        }

        public Criteria andApplydateLessThanOrEqualTo(String value) {
            addCriterion("applydate <=", value, "applydate");
            return this;
        }

        public Criteria andApplydateLike(String value) {
            addCriterion("applydate like", value, "applydate");
            return this;
        }

        public Criteria andApplydateNotLike(String value) {
            addCriterion("applydate not like", value, "applydate");
            return this;
        }

        public Criteria andApplydateIn(List<String> values) {
            addCriterion("applydate in", values, "applydate");
            return this;
        }

        public Criteria andApplydateNotIn(List<String> values) {
            addCriterion("applydate not in", values, "applydate");
            return this;
        }

        public Criteria andApplydateBetween(String value1, String value2) {
            addCriterion("applydate between", value1, value2, "applydate");
            return this;
        }

        public Criteria andApplydateNotBetween(String value1, String value2) {
            addCriterion("applydate not between", value1, value2, "applydate");
            return this;
        }

        public Criteria andTransdateIsNull() {
            addCriterion("transdate is null");
            return this;
        }

        public Criteria andTransdateIsNotNull() {
            addCriterion("transdate is not null");
            return this;
        }

        public Criteria andTransdateEqualTo(String value) {
            addCriterion("transdate =", value, "transdate");
            return this;
        }

        public Criteria andTransdateNotEqualTo(String value) {
            addCriterion("transdate <>", value, "transdate");
            return this;
        }

        public Criteria andTransdateGreaterThan(String value) {
            addCriterion("transdate >", value, "transdate");
            return this;
        }

        public Criteria andTransdateGreaterThanOrEqualTo(String value) {
            addCriterion("transdate >=", value, "transdate");
            return this;
        }

        public Criteria andTransdateLessThan(String value) {
            addCriterion("transdate <", value, "transdate");
            return this;
        }

        public Criteria andTransdateLessThanOrEqualTo(String value) {
            addCriterion("transdate <=", value, "transdate");
            return this;
        }

        public Criteria andTransdateLike(String value) {
            addCriterion("transdate like", value, "transdate");
            return this;
        }

        public Criteria andTransdateNotLike(String value) {
            addCriterion("transdate not like", value, "transdate");
            return this;
        }

        public Criteria andTransdateIn(List<String> values) {
            addCriterion("transdate in", values, "transdate");
            return this;
        }

        public Criteria andTransdateNotIn(List<String> values) {
            addCriterion("transdate not in", values, "transdate");
            return this;
        }

        public Criteria andTransdateBetween(String value1, String value2) {
            addCriterion("transdate between", value1, value2, "transdate");
            return this;
        }

        public Criteria andTransdateNotBetween(String value1, String value2) {
            addCriterion("transdate not between", value1, value2, "transdate");
            return this;
        }

        public Criteria andCardstatusIsNull() {
            addCriterion("cardstatus is null");
            return this;
        }

        public Criteria andCardstatusIsNotNull() {
            addCriterion("cardstatus is not null");
            return this;
        }

        public Criteria andCardstatusEqualTo(String value) {
            addCriterion("cardstatus =", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusNotEqualTo(String value) {
            addCriterion("cardstatus <>", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusGreaterThan(String value) {
            addCriterion("cardstatus >", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusGreaterThanOrEqualTo(String value) {
            addCriterion("cardstatus >=", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusLessThan(String value) {
            addCriterion("cardstatus <", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusLessThanOrEqualTo(String value) {
            addCriterion("cardstatus <=", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusLike(String value) {
            addCriterion("cardstatus like", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusNotLike(String value) {
            addCriterion("cardstatus not like", value, "cardstatus");
            return this;
        }

        public Criteria andCardstatusIn(List<String> values) {
            addCriterion("cardstatus in", values, "cardstatus");
            return this;
        }

        public Criteria andCardstatusNotIn(List<String> values) {
            addCriterion("cardstatus not in", values, "cardstatus");
            return this;
        }

        public Criteria andCardstatusBetween(String value1, String value2) {
            addCriterion("cardstatus between", value1, value2, "cardstatus");
            return this;
        }

        public Criteria andCardstatusNotBetween(String value1, String value2) {
            addCriterion("cardstatus not between", value1, value2, "cardstatus");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return this;
        }
    }
}