package com.pinelet.utp.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CardsyncExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public CardsyncExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    protected CardsyncExample(CardsyncExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andGprscodeIsNull() {
            addCriterion("GPRSCode is null");
            return this;
        }

        public Criteria andGprscodeIsNotNull() {
            addCriterion("GPRSCode is not null");
            return this;
        }

        public Criteria andGprscodeEqualTo(String value) {
            addCriterion("GPRSCode =", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotEqualTo(String value) {
            addCriterion("GPRSCode <>", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThan(String value) {
            addCriterion("GPRSCode >", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThanOrEqualTo(String value) {
            addCriterion("GPRSCode >=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThan(String value) {
            addCriterion("GPRSCode <", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThanOrEqualTo(String value) {
            addCriterion("GPRSCode <=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLike(String value) {
            addCriterion("GPRSCode like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotLike(String value) {
            addCriterion("GPRSCode not like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeIn(List<String> values) {
            addCriterion("GPRSCode in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotIn(List<String> values) {
            addCriterion("GPRSCode not in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeBetween(String value1, String value2) {
            addCriterion("GPRSCode between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotBetween(String value1, String value2) {
            addCriterion("GPRSCode not between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andCardcodeIsNull() {
            addCriterion("cardcode is null");
            return this;
        }

        public Criteria andCardcodeIsNotNull() {
            addCriterion("cardcode is not null");
            return this;
        }

        public Criteria andCardcodeEqualTo(String value) {
            addCriterion("cardcode =", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotEqualTo(String value) {
            addCriterion("cardcode <>", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeGreaterThan(String value) {
            addCriterion("cardcode >", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeGreaterThanOrEqualTo(String value) {
            addCriterion("cardcode >=", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLessThan(String value) {
            addCriterion("cardcode <", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLessThanOrEqualTo(String value) {
            addCriterion("cardcode <=", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLike(String value) {
            addCriterion("cardcode like", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotLike(String value) {
            addCriterion("cardcode not like", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeIn(List<String> values) {
            addCriterion("cardcode in", values, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotIn(List<String> values) {
            addCriterion("cardcode not in", values, "cardcode");
            return this;
        }

        public Criteria andCardcodeBetween(String value1, String value2) {
            addCriterion("cardcode between", value1, value2, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotBetween(String value1, String value2) {
            addCriterion("cardcode not between", value1, value2, "cardcode");
            return this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pId is null");
            return this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pId is not null");
            return this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pId =", value, "pid");
            return this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pId <>", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pId >", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pId >=", value, "pid");
            return this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pId <", value, "pid");
            return this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pId <=", value, "pid");
            return this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pId like", value, "pid");
            return this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pId not like", value, "pid");
            return this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pId in", values, "pid");
            return this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pId not in", values, "pid");
            return this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pId between", value1, value2, "pid");
            return this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pId not between", value1, value2, "pid");
            return this;
        }

        public Criteria andSynctypeIsNull() {
            addCriterion("synctype is null");
            return this;
        }

        public Criteria andSynctypeIsNotNull() {
            addCriterion("synctype is not null");
            return this;
        }

        public Criteria andSynctypeEqualTo(String value) {
            addCriterion("synctype =", value, "synctype");
            return this;
        }

        public Criteria andSynctypeNotEqualTo(String value) {
            addCriterion("synctype <>", value, "synctype");
            return this;
        }

        public Criteria andSynctypeGreaterThan(String value) {
            addCriterion("synctype >", value, "synctype");
            return this;
        }

        public Criteria andSynctypeGreaterThanOrEqualTo(String value) {
            addCriterion("synctype >=", value, "synctype");
            return this;
        }

        public Criteria andSynctypeLessThan(String value) {
            addCriterion("synctype <", value, "synctype");
            return this;
        }

        public Criteria andSynctypeLessThanOrEqualTo(String value) {
            addCriterion("synctype <=", value, "synctype");
            return this;
        }

        public Criteria andSynctypeLike(String value) {
            addCriterion("synctype like", value, "synctype");
            return this;
        }

        public Criteria andSynctypeNotLike(String value) {
            addCriterion("synctype not like", value, "synctype");
            return this;
        }

        public Criteria andSynctypeIn(List<String> values) {
            addCriterion("synctype in", values, "synctype");
            return this;
        }

        public Criteria andSynctypeNotIn(List<String> values) {
            addCriterion("synctype not in", values, "synctype");
            return this;
        }

        public Criteria andSynctypeBetween(String value1, String value2) {
            addCriterion("synctype between", value1, value2, "synctype");
            return this;
        }

        public Criteria andSynctypeNotBetween(String value1, String value2) {
            addCriterion("synctype not between", value1, value2, "synctype");
            return this;
        }

        public Criteria andSyncresultIsNull() {
            addCriterion("syncresult is null");
            return this;
        }

        public Criteria andSyncresultIsNotNull() {
            addCriterion("syncresult is not null");
            return this;
        }

        public Criteria andSyncresultEqualTo(String value) {
            addCriterion("syncresult =", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultNotEqualTo(String value) {
            addCriterion("syncresult <>", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultGreaterThan(String value) {
            addCriterion("syncresult >", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultGreaterThanOrEqualTo(String value) {
            addCriterion("syncresult >=", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultLessThan(String value) {
            addCriterion("syncresult <", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultLessThanOrEqualTo(String value) {
            addCriterion("syncresult <=", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultLike(String value) {
            addCriterion("syncresult like", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultNotLike(String value) {
            addCriterion("syncresult not like", value, "syncresult");
            return this;
        }

        public Criteria andSyncresultIn(List<String> values) {
            addCriterion("syncresult in", values, "syncresult");
            return this;
        }

        public Criteria andSyncresultNotIn(List<String> values) {
            addCriterion("syncresult not in", values, "syncresult");
            return this;
        }

        public Criteria andSyncresultBetween(String value1, String value2) {
            addCriterion("syncresult between", value1, value2, "syncresult");
            return this;
        }

        public Criteria andSyncresultNotBetween(String value1, String value2) {
            addCriterion("syncresult not between", value1, value2, "syncresult");
            return this;
        }

        public Criteria andRecordtimeIsNull() {
            addCriterion("recordtime is null");
            return this;
        }

        public Criteria andRecordtimeIsNotNull() {
            addCriterion("recordtime is not null");
            return this;
        }

        public Criteria andRecordtimeEqualTo(Long value) {
            addCriterion("recordtime =", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotEqualTo(Long value) {
            addCriterion("recordtime <>", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeGreaterThan(Long value) {
            addCriterion("recordtime >", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeGreaterThanOrEqualTo(Long value) {
            addCriterion("recordtime >=", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeLessThan(Long value) {
            addCriterion("recordtime <", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeLessThanOrEqualTo(Long value) {
            addCriterion("recordtime <=", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeIn(List<Long> values) {
            addCriterion("recordtime in", values, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotIn(List<Long> values) {
            addCriterion("recordtime not in", values, "recordtime");
            return this;
        }

        public Criteria andRecordtimeBetween(Long value1, Long value2) {
            addCriterion("recordtime between", value1, value2, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotBetween(Long value1, Long value2) {
            addCriterion("recordtime not between", value1, value2, "recordtime");
            return this;
        }

        public Criteria andSynctimeIsNull() {
            addCriterion("synctime is null");
            return this;
        }

        public Criteria andSynctimeIsNotNull() {
            addCriterion("synctime is not null");
            return this;
        }

        public Criteria andSynctimeEqualTo(Long value) {
            addCriterion("synctime =", value, "synctime");
            return this;
        }

        public Criteria andSynctimeNotEqualTo(Long value) {
            addCriterion("synctime <>", value, "synctime");
            return this;
        }

        public Criteria andSynctimeGreaterThan(Long value) {
            addCriterion("synctime >", value, "synctime");
            return this;
        }

        public Criteria andSynctimeGreaterThanOrEqualTo(Long value) {
            addCriterion("synctime >=", value, "synctime");
            return this;
        }

        public Criteria andSynctimeLessThan(Long value) {
            addCriterion("synctime <", value, "synctime");
            return this;
        }

        public Criteria andSynctimeLessThanOrEqualTo(Long value) {
            addCriterion("synctime <=", value, "synctime");
            return this;
        }

        public Criteria andSynctimeIn(List<Long> values) {
            addCriterion("synctime in", values, "synctime");
            return this;
        }

        public Criteria andSynctimeNotIn(List<Long> values) {
            addCriterion("synctime not in", values, "synctime");
            return this;
        }

        public Criteria andSynctimeBetween(Long value1, Long value2) {
            addCriterion("synctime between", value1, value2, "synctime");
            return this;
        }

        public Criteria andSynctimeNotBetween(Long value1, Long value2) {
            addCriterion("synctime not between", value1, value2, "synctime");
            return this;
        }
    }
}