package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;

public class Cardsync extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.ID
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private String id;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.GPRSCode
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private String gprscode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.cardcode
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private String cardcode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.pId
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private String pid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.synctype
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private String synctype;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.syncresult
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private String syncresult;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.recordtime
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private Long recordtime;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardsync.synctime
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private Long synctime;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.ID
     *
     * @return the value of cardsync.ID
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.ID
     *
     * @param id the value for cardsync.ID
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.GPRSCode
     *
     * @return the value of cardsync.GPRSCode
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getGprscode() {
        return gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.GPRSCode
     *
     * @param gprscode the value for cardsync.GPRSCode
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setGprscode(String gprscode) {
        this.gprscode = gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.cardcode
     *
     * @return the value of cardsync.cardcode
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.cardcode
     *
     * @param cardcode the value for cardsync.cardcode
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.pId
     *
     * @return the value of cardsync.pId
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.pId
     *
     * @param pid the value for cardsync.pId
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.synctype
     *
     * @return the value of cardsync.synctype
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getSynctype() {
        return synctype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.synctype
     *
     * @param synctype the value for cardsync.synctype
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setSynctype(String synctype) {
        this.synctype = synctype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.syncresult
     *
     * @return the value of cardsync.syncresult
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public String getSyncresult() {
        return syncresult;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.syncresult
     *
     * @param syncresult the value for cardsync.syncresult
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setSyncresult(String syncresult) {
        this.syncresult = syncresult;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.recordtime
     *
     * @return the value of cardsync.recordtime
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public Long getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.recordtime
     *
     * @param recordtime the value for cardsync.recordtime
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setRecordtime(Long recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardsync.synctime
     *
     * @return the value of cardsync.synctime
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public Long getSynctime() {
        return synctime;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardsync.synctime
     *
     * @param synctime the value for cardsync.synctime
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setSynctime(Long synctime) {
        this.synctime = synctime;
    }
}