package com.pinelet.utp.entity;

import java.math.BigDecimal;

public class Cardinfo extends CardinfoKey {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.cardname
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String cardname;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.phone
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String phone;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.address
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String address;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.balance
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private BigDecimal balance;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.applydate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String applydate;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.transdate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String transdate;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.cardstatus
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String cardstatus;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column cardinfo.remark
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String remark;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.cardname
     *
     * @return the value of cardinfo.cardname
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getCardname() {
        return cardname;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.cardname
     *
     * @param cardname the value for cardinfo.cardname
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setCardname(String cardname) {
        this.cardname = cardname;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.phone
     *
     * @return the value of cardinfo.phone
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.phone
     *
     * @param phone the value for cardinfo.phone
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.address
     *
     * @return the value of cardinfo.address
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.address
     *
     * @param address the value for cardinfo.address
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.balance
     *
     * @return the value of cardinfo.balance
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.balance
     *
     * @param balance the value for cardinfo.balance
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.applydate
     *
     * @return the value of cardinfo.applydate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getApplydate() {
        return applydate;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.applydate
     *
     * @param applydate the value for cardinfo.applydate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setApplydate(String applydate) {
        this.applydate = applydate;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.transdate
     *
     * @return the value of cardinfo.transdate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.transdate
     *
     * @param transdate the value for cardinfo.transdate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setTransdate(String transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.cardstatus
     *
     * @return the value of cardinfo.cardstatus
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getCardstatus() {
        return cardstatus;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.cardstatus
     *
     * @param cardstatus the value for cardinfo.cardstatus
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setCardstatus(String cardstatus) {
        this.cardstatus = cardstatus;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column cardinfo.remark
     *
     * @return the value of cardinfo.remark
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column cardinfo.remark
     *
     * @param remark the value for cardinfo.remark
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}