package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;

public class Commandinfo extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.commandId
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private String commandid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.pId
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private String pid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.GPRSCode
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private String gprscode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.commandtype
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private String commandtype;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.commandContent
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private String commandcontent;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.syncresult
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private String syncresult;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column commandinfo.recordtime
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    private Long recordtime;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.commandId
     *
     * @return the value of commandinfo.commandId
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public String getCommandid() {
        return commandid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.commandId
     *
     * @param commandid the value for commandinfo.commandId
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setCommandid(String commandid) {
        this.commandid = commandid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.pId
     *
     * @return the value of commandinfo.pId
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.pId
     *
     * @param pid the value for commandinfo.pId
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.GPRSCode
     *
     * @return the value of commandinfo.GPRSCode
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public String getGprscode() {
        return gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.GPRSCode
     *
     * @param gprscode the value for commandinfo.GPRSCode
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setGprscode(String gprscode) {
        this.gprscode = gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.commandtype
     *
     * @return the value of commandinfo.commandtype
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public String getCommandtype() {
        return commandtype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.commandtype
     *
     * @param commandtype the value for commandinfo.commandtype
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setCommandtype(String commandtype) {
        this.commandtype = commandtype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.commandContent
     *
     * @return the value of commandinfo.commandContent
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public String getCommandcontent() {
        return commandcontent;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.commandContent
     *
     * @param commandcontent the value for commandinfo.commandContent
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setCommandcontent(String commandcontent) {
        this.commandcontent = commandcontent;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.syncresult
     *
     * @return the value of commandinfo.syncresult
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public String getSyncresult() {
        return syncresult;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.syncresult
     *
     * @param syncresult the value for commandinfo.syncresult
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setSyncresult(String syncresult) {
        this.syncresult = syncresult;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column commandinfo.recordtime
     *
     * @return the value of commandinfo.recordtime
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public Long getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column commandinfo.recordtime
     *
     * @param recordtime the value for commandinfo.recordtime
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    public void setRecordtime(Long recordtime) {
        this.recordtime = recordtime;
    }
}