package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;

public class Devicerecord extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column devicerecord.GPRSCode
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private String gprscode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column devicerecord.recordType
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private String recordtype;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column devicerecord.devicetemp
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private String devicetemp;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column devicerecord.tdsel
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private String tdsel;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column devicerecord.ph
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private String ph;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column devicerecord.recordTime
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private String recordtime;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column devicerecord.GPRSCode
     *
     * @return the value of devicerecord.GPRSCode
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getGprscode() {
        return gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column devicerecord.GPRSCode
     *
     * @param gprscode the value for devicerecord.GPRSCode
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setGprscode(String gprscode) {
        this.gprscode = gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column devicerecord.recordType
     *
     * @return the value of devicerecord.recordType
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getRecordtype() {
        return recordtype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column devicerecord.recordType
     *
     * @param recordtype the value for devicerecord.recordType
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setRecordtype(String recordtype) {
        this.recordtype = recordtype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column devicerecord.devicetemp
     *
     * @return the value of devicerecord.devicetemp
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getDevicetemp() {
        return devicetemp;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column devicerecord.devicetemp
     *
     * @param devicetemp the value for devicerecord.devicetemp
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setDevicetemp(String devicetemp) {
        this.devicetemp = devicetemp;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column devicerecord.tdsel
     *
     * @return the value of devicerecord.tdsel
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getTdsel() {
        return tdsel;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column devicerecord.tdsel
     *
     * @param tdsel the value for devicerecord.tdsel
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setTdsel(String tdsel) {
        this.tdsel = tdsel;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column devicerecord.ph
     *
     * @return the value of devicerecord.ph
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getPh() {
        return ph;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column devicerecord.ph
     *
     * @param ph the value for devicerecord.ph
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setPh(String ph) {
        this.ph = ph;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column devicerecord.recordTime
     *
     * @return the value of devicerecord.recordTime
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column devicerecord.recordTime
     *
     * @param recordtime the value for devicerecord.recordTime
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setRecordtime(String recordtime) {
        this.recordtime = recordtime;
    }
}