package com.pinelet.utp.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DevicerecordExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public DevicerecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected DevicerecordExample(DevicerecordExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andGprscodeIsNull() {
            addCriterion("GPRSCode is null");
            return this;
        }

        public Criteria andGprscodeIsNotNull() {
            addCriterion("GPRSCode is not null");
            return this;
        }

        public Criteria andGprscodeEqualTo(String value) {
            addCriterion("GPRSCode =", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotEqualTo(String value) {
            addCriterion("GPRSCode <>", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThan(String value) {
            addCriterion("GPRSCode >", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThanOrEqualTo(String value) {
            addCriterion("GPRSCode >=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThan(String value) {
            addCriterion("GPRSCode <", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThanOrEqualTo(String value) {
            addCriterion("GPRSCode <=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLike(String value) {
            addCriterion("GPRSCode like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotLike(String value) {
            addCriterion("GPRSCode not like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeIn(List<String> values) {
            addCriterion("GPRSCode in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotIn(List<String> values) {
            addCriterion("GPRSCode not in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeBetween(String value1, String value2) {
            addCriterion("GPRSCode between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotBetween(String value1, String value2) {
            addCriterion("GPRSCode not between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andRecordtypeIsNull() {
            addCriterion("recordType is null");
            return this;
        }

        public Criteria andRecordtypeIsNotNull() {
            addCriterion("recordType is not null");
            return this;
        }

        public Criteria andRecordtypeEqualTo(String value) {
            addCriterion("recordType =", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeNotEqualTo(String value) {
            addCriterion("recordType <>", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeGreaterThan(String value) {
            addCriterion("recordType >", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeGreaterThanOrEqualTo(String value) {
            addCriterion("recordType >=", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeLessThan(String value) {
            addCriterion("recordType <", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeLessThanOrEqualTo(String value) {
            addCriterion("recordType <=", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeLike(String value) {
            addCriterion("recordType like", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeNotLike(String value) {
            addCriterion("recordType not like", value, "recordtype");
            return this;
        }

        public Criteria andRecordtypeIn(List<String> values) {
            addCriterion("recordType in", values, "recordtype");
            return this;
        }

        public Criteria andRecordtypeNotIn(List<String> values) {
            addCriterion("recordType not in", values, "recordtype");
            return this;
        }

        public Criteria andRecordtypeBetween(String value1, String value2) {
            addCriterion("recordType between", value1, value2, "recordtype");
            return this;
        }

        public Criteria andRecordtypeNotBetween(String value1, String value2) {
            addCriterion("recordType not between", value1, value2, "recordtype");
            return this;
        }

        public Criteria andDevicetempIsNull() {
            addCriterion("devicetemp is null");
            return this;
        }

        public Criteria andDevicetempIsNotNull() {
            addCriterion("devicetemp is not null");
            return this;
        }

        public Criteria andDevicetempEqualTo(String value) {
            addCriterion("devicetemp =", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempNotEqualTo(String value) {
            addCriterion("devicetemp <>", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempGreaterThan(String value) {
            addCriterion("devicetemp >", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempGreaterThanOrEqualTo(String value) {
            addCriterion("devicetemp >=", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempLessThan(String value) {
            addCriterion("devicetemp <", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempLessThanOrEqualTo(String value) {
            addCriterion("devicetemp <=", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempLike(String value) {
            addCriterion("devicetemp like", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempNotLike(String value) {
            addCriterion("devicetemp not like", value, "devicetemp");
            return this;
        }

        public Criteria andDevicetempIn(List<String> values) {
            addCriterion("devicetemp in", values, "devicetemp");
            return this;
        }

        public Criteria andDevicetempNotIn(List<String> values) {
            addCriterion("devicetemp not in", values, "devicetemp");
            return this;
        }

        public Criteria andDevicetempBetween(String value1, String value2) {
            addCriterion("devicetemp between", value1, value2, "devicetemp");
            return this;
        }

        public Criteria andDevicetempNotBetween(String value1, String value2) {
            addCriterion("devicetemp not between", value1, value2, "devicetemp");
            return this;
        }

        public Criteria andTdselIsNull() {
            addCriterion("tdsel is null");
            return this;
        }

        public Criteria andTdselIsNotNull() {
            addCriterion("tdsel is not null");
            return this;
        }

        public Criteria andTdselEqualTo(String value) {
            addCriterion("tdsel =", value, "tdsel");
            return this;
        }

        public Criteria andTdselNotEqualTo(String value) {
            addCriterion("tdsel <>", value, "tdsel");
            return this;
        }

        public Criteria andTdselGreaterThan(String value) {
            addCriterion("tdsel >", value, "tdsel");
            return this;
        }

        public Criteria andTdselGreaterThanOrEqualTo(String value) {
            addCriterion("tdsel >=", value, "tdsel");
            return this;
        }

        public Criteria andTdselLessThan(String value) {
            addCriterion("tdsel <", value, "tdsel");
            return this;
        }

        public Criteria andTdselLessThanOrEqualTo(String value) {
            addCriterion("tdsel <=", value, "tdsel");
            return this;
        }

        public Criteria andTdselLike(String value) {
            addCriterion("tdsel like", value, "tdsel");
            return this;
        }

        public Criteria andTdselNotLike(String value) {
            addCriterion("tdsel not like", value, "tdsel");
            return this;
        }

        public Criteria andTdselIn(List<String> values) {
            addCriterion("tdsel in", values, "tdsel");
            return this;
        }

        public Criteria andTdselNotIn(List<String> values) {
            addCriterion("tdsel not in", values, "tdsel");
            return this;
        }

        public Criteria andTdselBetween(String value1, String value2) {
            addCriterion("tdsel between", value1, value2, "tdsel");
            return this;
        }

        public Criteria andTdselNotBetween(String value1, String value2) {
            addCriterion("tdsel not between", value1, value2, "tdsel");
            return this;
        }

        public Criteria andPhIsNull() {
            addCriterion("ph is null");
            return this;
        }

        public Criteria andPhIsNotNull() {
            addCriterion("ph is not null");
            return this;
        }

        public Criteria andPhEqualTo(String value) {
            addCriterion("ph =", value, "ph");
            return this;
        }

        public Criteria andPhNotEqualTo(String value) {
            addCriterion("ph <>", value, "ph");
            return this;
        }

        public Criteria andPhGreaterThan(String value) {
            addCriterion("ph >", value, "ph");
            return this;
        }

        public Criteria andPhGreaterThanOrEqualTo(String value) {
            addCriterion("ph >=", value, "ph");
            return this;
        }

        public Criteria andPhLessThan(String value) {
            addCriterion("ph <", value, "ph");
            return this;
        }

        public Criteria andPhLessThanOrEqualTo(String value) {
            addCriterion("ph <=", value, "ph");
            return this;
        }

        public Criteria andPhLike(String value) {
            addCriterion("ph like", value, "ph");
            return this;
        }

        public Criteria andPhNotLike(String value) {
            addCriterion("ph not like", value, "ph");
            return this;
        }

        public Criteria andPhIn(List<String> values) {
            addCriterion("ph in", values, "ph");
            return this;
        }

        public Criteria andPhNotIn(List<String> values) {
            addCriterion("ph not in", values, "ph");
            return this;
        }

        public Criteria andPhBetween(String value1, String value2) {
            addCriterion("ph between", value1, value2, "ph");
            return this;
        }

        public Criteria andPhNotBetween(String value1, String value2) {
            addCriterion("ph not between", value1, value2, "ph");
            return this;
        }

        public Criteria andRecordtimeIsNull() {
            addCriterion("recordTime is null");
            return this;
        }

        public Criteria andRecordtimeIsNotNull() {
            addCriterion("recordTime is not null");
            return this;
        }

        public Criteria andRecordtimeEqualTo(String value) {
            addCriterion("recordTime =", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotEqualTo(String value) {
            addCriterion("recordTime <>", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeGreaterThan(String value) {
            addCriterion("recordTime >", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeGreaterThanOrEqualTo(String value) {
            addCriterion("recordTime >=", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeLessThan(String value) {
            addCriterion("recordTime <", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeLessThanOrEqualTo(String value) {
            addCriterion("recordTime <=", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeLike(String value) {
            addCriterion("recordTime like", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotLike(String value) {
            addCriterion("recordTime not like", value, "recordtime");
            return this;
        }

        public Criteria andRecordtimeIn(List<String> values) {
            addCriterion("recordTime in", values, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotIn(List<String> values) {
            addCriterion("recordTime not in", values, "recordtime");
            return this;
        }

        public Criteria andRecordtimeBetween(String value1, String value2) {
            addCriterion("recordTime between", value1, value2, "recordtime");
            return this;
        }

        public Criteria andRecordtimeNotBetween(String value1, String value2) {
            addCriterion("recordTime not between", value1, value2, "recordtime");
            return this;
        }
    }
}