package com.pinelet.utp.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeviceinfoExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public DeviceinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    protected DeviceinfoExample(DeviceinfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andGprscodeIsNull() {
            addCriterion("GPRSCode is null");
            return this;
        }

        public Criteria andGprscodeIsNotNull() {
            addCriterion("GPRSCode is not null");
            return this;
        }

        public Criteria andGprscodeEqualTo(String value) {
            addCriterion("GPRSCode =", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotEqualTo(String value) {
            addCriterion("GPRSCode <>", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThan(String value) {
            addCriterion("GPRSCode >", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThanOrEqualTo(String value) {
            addCriterion("GPRSCode >=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThan(String value) {
            addCriterion("GPRSCode <", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThanOrEqualTo(String value) {
            addCriterion("GPRSCode <=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLike(String value) {
            addCriterion("GPRSCode like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotLike(String value) {
            addCriterion("GPRSCode not like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeIn(List<String> values) {
            addCriterion("GPRSCode in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotIn(List<String> values) {
            addCriterion("GPRSCode not in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeBetween(String value1, String value2) {
            addCriterion("GPRSCode between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotBetween(String value1, String value2) {
            addCriterion("GPRSCode not between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andDevicecodeIsNull() {
            addCriterion("deviceCode is null");
            return this;
        }

        public Criteria andDevicecodeIsNotNull() {
            addCriterion("deviceCode is not null");
            return this;
        }

        public Criteria andDevicecodeEqualTo(String value) {
            addCriterion("deviceCode =", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeNotEqualTo(String value) {
            addCriterion("deviceCode <>", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeGreaterThan(String value) {
            addCriterion("deviceCode >", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeGreaterThanOrEqualTo(String value) {
            addCriterion("deviceCode >=", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeLessThan(String value) {
            addCriterion("deviceCode <", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeLessThanOrEqualTo(String value) {
            addCriterion("deviceCode <=", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeLike(String value) {
            addCriterion("deviceCode like", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeNotLike(String value) {
            addCriterion("deviceCode not like", value, "devicecode");
            return this;
        }

        public Criteria andDevicecodeIn(List<String> values) {
            addCriterion("deviceCode in", values, "devicecode");
            return this;
        }

        public Criteria andDevicecodeNotIn(List<String> values) {
            addCriterion("deviceCode not in", values, "devicecode");
            return this;
        }

        public Criteria andDevicecodeBetween(String value1, String value2) {
            addCriterion("deviceCode between", value1, value2, "devicecode");
            return this;
        }

        public Criteria andDevicecodeNotBetween(String value1, String value2) {
            addCriterion("deviceCode not between", value1, value2, "devicecode");
            return this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pId is null");
            return this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pId is not null");
            return this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pId =", value, "pid");
            return this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pId <>", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pId >", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pId >=", value, "pid");
            return this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pId <", value, "pid");
            return this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pId <=", value, "pid");
            return this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pId like", value, "pid");
            return this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pId not like", value, "pid");
            return this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pId in", values, "pid");
            return this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pId not in", values, "pid");
            return this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pId between", value1, value2, "pid");
            return this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pId not between", value1, value2, "pid");
            return this;
        }

        public Criteria andPhonecodeIsNull() {
            addCriterion("phoneCode is null");
            return this;
        }

        public Criteria andPhonecodeIsNotNull() {
            addCriterion("phoneCode is not null");
            return this;
        }

        public Criteria andPhonecodeEqualTo(String value) {
            addCriterion("phoneCode =", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeNotEqualTo(String value) {
            addCriterion("phoneCode <>", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeGreaterThan(String value) {
            addCriterion("phoneCode >", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeGreaterThanOrEqualTo(String value) {
            addCriterion("phoneCode >=", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeLessThan(String value) {
            addCriterion("phoneCode <", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeLessThanOrEqualTo(String value) {
            addCriterion("phoneCode <=", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeLike(String value) {
            addCriterion("phoneCode like", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeNotLike(String value) {
            addCriterion("phoneCode not like", value, "phonecode");
            return this;
        }

        public Criteria andPhonecodeIn(List<String> values) {
            addCriterion("phoneCode in", values, "phonecode");
            return this;
        }

        public Criteria andPhonecodeNotIn(List<String> values) {
            addCriterion("phoneCode not in", values, "phonecode");
            return this;
        }

        public Criteria andPhonecodeBetween(String value1, String value2) {
            addCriterion("phoneCode between", value1, value2, "phonecode");
            return this;
        }

        public Criteria andPhonecodeNotBetween(String value1, String value2) {
            addCriterion("phoneCode not between", value1, value2, "phonecode");
            return this;
        }

        public Criteria andModelIsNull() {
            addCriterion("Model is null");
            return this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("Model is not null");
            return this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("Model =", value, "model");
            return this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("Model <>", value, "model");
            return this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("Model >", value, "model");
            return this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("Model >=", value, "model");
            return this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("Model <", value, "model");
            return this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("Model <=", value, "model");
            return this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("Model like", value, "model");
            return this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("Model not like", value, "model");
            return this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("Model in", values, "model");
            return this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("Model not in", values, "model");
            return this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("Model between", value1, value2, "model");
            return this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("Model not between", value1, value2, "model");
            return this;
        }

        public Criteria andContactcallIsNull() {
            addCriterion("contactCall is null");
            return this;
        }

        public Criteria andContactcallIsNotNull() {
            addCriterion("contactCall is not null");
            return this;
        }

        public Criteria andContactcallEqualTo(String value) {
            addCriterion("contactCall =", value, "contactcall");
            return this;
        }

        public Criteria andContactcallNotEqualTo(String value) {
            addCriterion("contactCall <>", value, "contactcall");
            return this;
        }

        public Criteria andContactcallGreaterThan(String value) {
            addCriterion("contactCall >", value, "contactcall");
            return this;
        }

        public Criteria andContactcallGreaterThanOrEqualTo(String value) {
            addCriterion("contactCall >=", value, "contactcall");
            return this;
        }

        public Criteria andContactcallLessThan(String value) {
            addCriterion("contactCall <", value, "contactcall");
            return this;
        }

        public Criteria andContactcallLessThanOrEqualTo(String value) {
            addCriterion("contactCall <=", value, "contactcall");
            return this;
        }

        public Criteria andContactcallLike(String value) {
            addCriterion("contactCall like", value, "contactcall");
            return this;
        }

        public Criteria andContactcallNotLike(String value) {
            addCriterion("contactCall not like", value, "contactcall");
            return this;
        }

        public Criteria andContactcallIn(List<String> values) {
            addCriterion("contactCall in", values, "contactcall");
            return this;
        }

        public Criteria andContactcallNotIn(List<String> values) {
            addCriterion("contactCall not in", values, "contactcall");
            return this;
        }

        public Criteria andContactcallBetween(String value1, String value2) {
            addCriterion("contactCall between", value1, value2, "contactcall");
            return this;
        }

        public Criteria andContactcallNotBetween(String value1, String value2) {
            addCriterion("contactCall not between", value1, value2, "contactcall");
            return this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("Address in", values, "address");
            return this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("Address not in", values, "address");
            return this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return this;
        }

        public Criteria andPpdateIsNull() {
            addCriterion("ppDate is null");
            return this;
        }

        public Criteria andPpdateIsNotNull() {
            addCriterion("ppDate is not null");
            return this;
        }

        public Criteria andPpdateEqualTo(String value) {
            addCriterion("ppDate =", value, "ppdate");
            return this;
        }

        public Criteria andPpdateNotEqualTo(String value) {
            addCriterion("ppDate <>", value, "ppdate");
            return this;
        }

        public Criteria andPpdateGreaterThan(String value) {
            addCriterion("ppDate >", value, "ppdate");
            return this;
        }

        public Criteria andPpdateGreaterThanOrEqualTo(String value) {
            addCriterion("ppDate >=", value, "ppdate");
            return this;
        }

        public Criteria andPpdateLessThan(String value) {
            addCriterion("ppDate <", value, "ppdate");
            return this;
        }

        public Criteria andPpdateLessThanOrEqualTo(String value) {
            addCriterion("ppDate <=", value, "ppdate");
            return this;
        }

        public Criteria andPpdateLike(String value) {
            addCriterion("ppDate like", value, "ppdate");
            return this;
        }

        public Criteria andPpdateNotLike(String value) {
            addCriterion("ppDate not like", value, "ppdate");
            return this;
        }

        public Criteria andPpdateIn(List<String> values) {
            addCriterion("ppDate in", values, "ppdate");
            return this;
        }

        public Criteria andPpdateNotIn(List<String> values) {
            addCriterion("ppDate not in", values, "ppdate");
            return this;
        }

        public Criteria andPpdateBetween(String value1, String value2) {
            addCriterion("ppDate between", value1, value2, "ppdate");
            return this;
        }

        public Criteria andPpdateNotBetween(String value1, String value2) {
            addCriterion("ppDate not between", value1, value2, "ppdate");
            return this;
        }

        public Criteria andCarbondateIsNull() {
            addCriterion("carbonDate is null");
            return this;
        }

        public Criteria andCarbondateIsNotNull() {
            addCriterion("carbonDate is not null");
            return this;
        }

        public Criteria andCarbondateEqualTo(String value) {
            addCriterion("carbonDate =", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateNotEqualTo(String value) {
            addCriterion("carbonDate <>", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateGreaterThan(String value) {
            addCriterion("carbonDate >", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateGreaterThanOrEqualTo(String value) {
            addCriterion("carbonDate >=", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateLessThan(String value) {
            addCriterion("carbonDate <", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateLessThanOrEqualTo(String value) {
            addCriterion("carbonDate <=", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateLike(String value) {
            addCriterion("carbonDate like", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateNotLike(String value) {
            addCriterion("carbonDate not like", value, "carbondate");
            return this;
        }

        public Criteria andCarbondateIn(List<String> values) {
            addCriterion("carbonDate in", values, "carbondate");
            return this;
        }

        public Criteria andCarbondateNotIn(List<String> values) {
            addCriterion("carbonDate not in", values, "carbondate");
            return this;
        }

        public Criteria andCarbondateBetween(String value1, String value2) {
            addCriterion("carbonDate between", value1, value2, "carbondate");
            return this;
        }

        public Criteria andCarbondateNotBetween(String value1, String value2) {
            addCriterion("carbonDate not between", value1, value2, "carbondate");
            return this;
        }

        public Criteria andRodateIsNull() {
            addCriterion("roDate is null");
            return this;
        }

        public Criteria andRodateIsNotNull() {
            addCriterion("roDate is not null");
            return this;
        }

        public Criteria andRodateEqualTo(String value) {
            addCriterion("roDate =", value, "rodate");
            return this;
        }

        public Criteria andRodateNotEqualTo(String value) {
            addCriterion("roDate <>", value, "rodate");
            return this;
        }

        public Criteria andRodateGreaterThan(String value) {
            addCriterion("roDate >", value, "rodate");
            return this;
        }

        public Criteria andRodateGreaterThanOrEqualTo(String value) {
            addCriterion("roDate >=", value, "rodate");
            return this;
        }

        public Criteria andRodateLessThan(String value) {
            addCriterion("roDate <", value, "rodate");
            return this;
        }

        public Criteria andRodateLessThanOrEqualTo(String value) {
            addCriterion("roDate <=", value, "rodate");
            return this;
        }

        public Criteria andRodateLike(String value) {
            addCriterion("roDate like", value, "rodate");
            return this;
        }

        public Criteria andRodateNotLike(String value) {
            addCriterion("roDate not like", value, "rodate");
            return this;
        }

        public Criteria andRodateIn(List<String> values) {
            addCriterion("roDate in", values, "rodate");
            return this;
        }

        public Criteria andRodateNotIn(List<String> values) {
            addCriterion("roDate not in", values, "rodate");
            return this;
        }

        public Criteria andRodateBetween(String value1, String value2) {
            addCriterion("roDate between", value1, value2, "rodate");
            return this;
        }

        public Criteria andRodateNotBetween(String value1, String value2) {
            addCriterion("roDate not between", value1, value2, "rodate");
            return this;
        }

        public Criteria andMinedateIsNull() {
            addCriterion("mineDate is null");
            return this;
        }

        public Criteria andMinedateIsNotNull() {
            addCriterion("mineDate is not null");
            return this;
        }

        public Criteria andMinedateEqualTo(String value) {
            addCriterion("mineDate =", value, "minedate");
            return this;
        }

        public Criteria andMinedateNotEqualTo(String value) {
            addCriterion("mineDate <>", value, "minedate");
            return this;
        }

        public Criteria andMinedateGreaterThan(String value) {
            addCriterion("mineDate >", value, "minedate");
            return this;
        }

        public Criteria andMinedateGreaterThanOrEqualTo(String value) {
            addCriterion("mineDate >=", value, "minedate");
            return this;
        }

        public Criteria andMinedateLessThan(String value) {
            addCriterion("mineDate <", value, "minedate");
            return this;
        }

        public Criteria andMinedateLessThanOrEqualTo(String value) {
            addCriterion("mineDate <=", value, "minedate");
            return this;
        }

        public Criteria andMinedateLike(String value) {
            addCriterion("mineDate like", value, "minedate");
            return this;
        }

        public Criteria andMinedateNotLike(String value) {
            addCriterion("mineDate not like", value, "minedate");
            return this;
        }

        public Criteria andMinedateIn(List<String> values) {
            addCriterion("mineDate in", values, "minedate");
            return this;
        }

        public Criteria andMinedateNotIn(List<String> values) {
            addCriterion("mineDate not in", values, "minedate");
            return this;
        }

        public Criteria andMinedateBetween(String value1, String value2) {
            addCriterion("mineDate between", value1, value2, "minedate");
            return this;
        }

        public Criteria andMinedateNotBetween(String value1, String value2) {
            addCriterion("mineDate not between", value1, value2, "minedate");
            return this;
        }

        public Criteria andDevicestatusIsNull() {
            addCriterion("deviceStatus is null");
            return this;
        }

        public Criteria andDevicestatusIsNotNull() {
            addCriterion("deviceStatus is not null");
            return this;
        }

        public Criteria andDevicestatusEqualTo(String value) {
            addCriterion("deviceStatus =", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusNotEqualTo(String value) {
            addCriterion("deviceStatus <>", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusGreaterThan(String value) {
            addCriterion("deviceStatus >", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusGreaterThanOrEqualTo(String value) {
            addCriterion("deviceStatus >=", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusLessThan(String value) {
            addCriterion("deviceStatus <", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusLessThanOrEqualTo(String value) {
            addCriterion("deviceStatus <=", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusLike(String value) {
            addCriterion("deviceStatus like", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusNotLike(String value) {
            addCriterion("deviceStatus not like", value, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusIn(List<String> values) {
            addCriterion("deviceStatus in", values, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusNotIn(List<String> values) {
            addCriterion("deviceStatus not in", values, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusBetween(String value1, String value2) {
            addCriterion("deviceStatus between", value1, value2, "devicestatus");
            return this;
        }

        public Criteria andDevicestatusNotBetween(String value1, String value2) {
            addCriterion("deviceStatus not between", value1, value2, "devicestatus");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return this;
        }

        public Criteria andDeadlineEqualTo(String value) {
            addCriterion("deadline =", value, "deadline");
            return this;
        }

        public Criteria andDeadlineNotEqualTo(String value) {
            addCriterion("deadline <>", value, "deadline");
            return this;
        }

        public Criteria andDeadlineGreaterThan(String value) {
            addCriterion("deadline >", value, "deadline");
            return this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("deadline >=", value, "deadline");
            return this;
        }

        public Criteria andDeadlineLessThan(String value) {
            addCriterion("deadline <", value, "deadline");
            return this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(String value) {
            addCriterion("deadline <=", value, "deadline");
            return this;
        }

        public Criteria andDeadlineLike(String value) {
            addCriterion("deadline like", value, "deadline");
            return this;
        }

        public Criteria andDeadlineNotLike(String value) {
            addCriterion("deadline not like", value, "deadline");
            return this;
        }

        public Criteria andDeadlineIn(List<String> values) {
            addCriterion("deadline in", values, "deadline");
            return this;
        }

        public Criteria andDeadlineNotIn(List<String> values) {
            addCriterion("deadline not in", values, "deadline");
            return this;
        }

        public Criteria andDeadlineBetween(String value1, String value2) {
            addCriterion("deadline between", value1, value2, "deadline");
            return this;
        }

        public Criteria andDeadlineNotBetween(String value1, String value2) {
            addCriterion("deadline not between", value1, value2, "deadline");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return this;
        }
    }
}