package com.pinelet.utp.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeviceworkExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public DeviceworkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected DeviceworkExample(DeviceworkExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andGprscodeIsNull() {
            addCriterion("GPRSCode is null");
            return this;
        }

        public Criteria andGprscodeIsNotNull() {
            addCriterion("GPRSCode is not null");
            return this;
        }

        public Criteria andGprscodeEqualTo(String value) {
            addCriterion("GPRSCode =", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotEqualTo(String value) {
            addCriterion("GPRSCode <>", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThan(String value) {
            addCriterion("GPRSCode >", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThanOrEqualTo(String value) {
            addCriterion("GPRSCode >=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThan(String value) {
            addCriterion("GPRSCode <", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThanOrEqualTo(String value) {
            addCriterion("GPRSCode <=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLike(String value) {
            addCriterion("GPRSCode like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotLike(String value) {
            addCriterion("GPRSCode not like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeIn(List<String> values) {
            addCriterion("GPRSCode in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotIn(List<String> values) {
            addCriterion("GPRSCode not in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeBetween(String value1, String value2) {
            addCriterion("GPRSCode between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotBetween(String value1, String value2) {
            addCriterion("GPRSCode not between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andCardcomIsNull() {
            addCriterion("cardcom is null");
            return this;
        }

        public Criteria andCardcomIsNotNull() {
            addCriterion("cardcom is not null");
            return this;
        }

        public Criteria andCardcomEqualTo(Boolean value) {
            addCriterion("cardcom =", value, "cardcom");
            return this;
        }

        public Criteria andCardcomNotEqualTo(Boolean value) {
            addCriterion("cardcom <>", value, "cardcom");
            return this;
        }

        public Criteria andCardcomGreaterThan(Boolean value) {
            addCriterion("cardcom >", value, "cardcom");
            return this;
        }

        public Criteria andCardcomGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cardcom >=", value, "cardcom");
            return this;
        }

        public Criteria andCardcomLessThan(Boolean value) {
            addCriterion("cardcom <", value, "cardcom");
            return this;
        }

        public Criteria andCardcomLessThanOrEqualTo(Boolean value) {
            addCriterion("cardcom <=", value, "cardcom");
            return this;
        }

        public Criteria andCardcomIn(List<Boolean> values) {
            addCriterion("cardcom in", values, "cardcom");
            return this;
        }

        public Criteria andCardcomNotIn(List<Boolean> values) {
            addCriterion("cardcom not in", values, "cardcom");
            return this;
        }

        public Criteria andCardcomBetween(Boolean value1, Boolean value2) {
            addCriterion("cardcom between", value1, value2, "cardcom");
            return this;
        }

        public Criteria andCardcomNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cardcom not between", value1, value2, "cardcom");
            return this;
        }

        public Criteria andLowpressureIsNull() {
            addCriterion("lowpressure is null");
            return this;
        }

        public Criteria andLowpressureIsNotNull() {
            addCriterion("lowpressure is not null");
            return this;
        }

        public Criteria andLowpressureEqualTo(Boolean value) {
            addCriterion("lowpressure =", value, "lowpressure");
            return this;
        }

        public Criteria andLowpressureNotEqualTo(Boolean value) {
            addCriterion("lowpressure <>", value, "lowpressure");
            return this;
        }

        public Criteria andLowpressureGreaterThan(Boolean value) {
            addCriterion("lowpressure >", value, "lowpressure");
            return this;
        }

        public Criteria andLowpressureGreaterThanOrEqualTo(Boolean value) {
            addCriterion("lowpressure >=", value, "lowpressure");
            return this;
        }

        public Criteria andLowpressureLessThan(Boolean value) {
            addCriterion("lowpressure <", value, "lowpressure");
            return this;
        }

        public Criteria andLowpressureLessThanOrEqualTo(Boolean value) {
            addCriterion("lowpressure <=", value, "lowpressure");
            return this;
        }

        public Criteria andLowpressureIn(List<Boolean> values) {
            addCriterion("lowpressure in", values, "lowpressure");
            return this;
        }

        public Criteria andLowpressureNotIn(List<Boolean> values) {
            addCriterion("lowpressure not in", values, "lowpressure");
            return this;
        }

        public Criteria andLowpressureBetween(Boolean value1, Boolean value2) {
            addCriterion("lowpressure between", value1, value2, "lowpressure");
            return this;
        }

        public Criteria andLowpressureNotBetween(Boolean value1, Boolean value2) {
            addCriterion("lowpressure not between", value1, value2, "lowpressure");
            return this;
        }

        public Criteria andHighpositionIsNull() {
            addCriterion("highposition is null");
            return this;
        }

        public Criteria andHighpositionIsNotNull() {
            addCriterion("highposition is not null");
            return this;
        }

        public Criteria andHighpositionEqualTo(Boolean value) {
            addCriterion("highposition =", value, "highposition");
            return this;
        }

        public Criteria andHighpositionNotEqualTo(Boolean value) {
            addCriterion("highposition <>", value, "highposition");
            return this;
        }

        public Criteria andHighpositionGreaterThan(Boolean value) {
            addCriterion("highposition >", value, "highposition");
            return this;
        }

        public Criteria andHighpositionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("highposition >=", value, "highposition");
            return this;
        }

        public Criteria andHighpositionLessThan(Boolean value) {
            addCriterion("highposition <", value, "highposition");
            return this;
        }

        public Criteria andHighpositionLessThanOrEqualTo(Boolean value) {
            addCriterion("highposition <=", value, "highposition");
            return this;
        }

        public Criteria andHighpositionIn(List<Boolean> values) {
            addCriterion("highposition in", values, "highposition");
            return this;
        }

        public Criteria andHighpositionNotIn(List<Boolean> values) {
            addCriterion("highposition not in", values, "highposition");
            return this;
        }

        public Criteria andHighpositionBetween(Boolean value1, Boolean value2) {
            addCriterion("highposition between", value1, value2, "highposition");
            return this;
        }

        public Criteria andHighpositionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("highposition not between", value1, value2, "highposition");
            return this;
        }

        public Criteria andLowpositionIsNull() {
            addCriterion("lowposition is null");
            return this;
        }

        public Criteria andLowpositionIsNotNull() {
            addCriterion("lowposition is not null");
            return this;
        }

        public Criteria andLowpositionEqualTo(Boolean value) {
            addCriterion("lowposition =", value, "lowposition");
            return this;
        }

        public Criteria andLowpositionNotEqualTo(Boolean value) {
            addCriterion("lowposition <>", value, "lowposition");
            return this;
        }

        public Criteria andLowpositionGreaterThan(Boolean value) {
            addCriterion("lowposition >", value, "lowposition");
            return this;
        }

        public Criteria andLowpositionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("lowposition >=", value, "lowposition");
            return this;
        }

        public Criteria andLowpositionLessThan(Boolean value) {
            addCriterion("lowposition <", value, "lowposition");
            return this;
        }

        public Criteria andLowpositionLessThanOrEqualTo(Boolean value) {
            addCriterion("lowposition <=", value, "lowposition");
            return this;
        }

        public Criteria andLowpositionIn(List<Boolean> values) {
            addCriterion("lowposition in", values, "lowposition");
            return this;
        }

        public Criteria andLowpositionNotIn(List<Boolean> values) {
            addCriterion("lowposition not in", values, "lowposition");
            return this;
        }

        public Criteria andLowpositionBetween(Boolean value1, Boolean value2) {
            addCriterion("lowposition between", value1, value2, "lowposition");
            return this;
        }

        public Criteria andLowpositionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("lowposition not between", value1, value2, "lowposition");
            return this;
        }

        public Criteria andMakewaterIsNull() {
            addCriterion("makewater is null");
            return this;
        }

        public Criteria andMakewaterIsNotNull() {
            addCriterion("makewater is not null");
            return this;
        }

        public Criteria andMakewaterEqualTo(Boolean value) {
            addCriterion("makewater =", value, "makewater");
            return this;
        }

        public Criteria andMakewaterNotEqualTo(Boolean value) {
            addCriterion("makewater <>", value, "makewater");
            return this;
        }

        public Criteria andMakewaterGreaterThan(Boolean value) {
            addCriterion("makewater >", value, "makewater");
            return this;
        }

        public Criteria andMakewaterGreaterThanOrEqualTo(Boolean value) {
            addCriterion("makewater >=", value, "makewater");
            return this;
        }

        public Criteria andMakewaterLessThan(Boolean value) {
            addCriterion("makewater <", value, "makewater");
            return this;
        }

        public Criteria andMakewaterLessThanOrEqualTo(Boolean value) {
            addCriterion("makewater <=", value, "makewater");
            return this;
        }

        public Criteria andMakewaterIn(List<Boolean> values) {
            addCriterion("makewater in", values, "makewater");
            return this;
        }

        public Criteria andMakewaterNotIn(List<Boolean> values) {
            addCriterion("makewater not in", values, "makewater");
            return this;
        }

        public Criteria andMakewaterBetween(Boolean value1, Boolean value2) {
            addCriterion("makewater between", value1, value2, "makewater");
            return this;
        }

        public Criteria andMakewaterNotBetween(Boolean value1, Boolean value2) {
            addCriterion("makewater not between", value1, value2, "makewater");
            return this;
        }

        public Criteria andOffsaleIsNull() {
            addCriterion("offsale is null");
            return this;
        }

        public Criteria andOffsaleIsNotNull() {
            addCriterion("offsale is not null");
            return this;
        }

        public Criteria andOffsaleEqualTo(Boolean value) {
            addCriterion("offsale =", value, "offsale");
            return this;
        }

        public Criteria andOffsaleNotEqualTo(Boolean value) {
            addCriterion("offsale <>", value, "offsale");
            return this;
        }

        public Criteria andOffsaleGreaterThan(Boolean value) {
            addCriterion("offsale >", value, "offsale");
            return this;
        }

        public Criteria andOffsaleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("offsale >=", value, "offsale");
            return this;
        }

        public Criteria andOffsaleLessThan(Boolean value) {
            addCriterion("offsale <", value, "offsale");
            return this;
        }

        public Criteria andOffsaleLessThanOrEqualTo(Boolean value) {
            addCriterion("offsale <=", value, "offsale");
            return this;
        }

        public Criteria andOffsaleIn(List<Boolean> values) {
            addCriterion("offsale in", values, "offsale");
            return this;
        }

        public Criteria andOffsaleNotIn(List<Boolean> values) {
            addCriterion("offsale not in", values, "offsale");
            return this;
        }

        public Criteria andOffsaleBetween(Boolean value1, Boolean value2) {
            addCriterion("offsale between", value1, value2, "offsale");
            return this;
        }

        public Criteria andOffsaleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("offsale not between", value1, value2, "offsale");
            return this;
        }

        public Criteria andOnsaleIsNull() {
            addCriterion("onsale is null");
            return this;
        }

        public Criteria andOnsaleIsNotNull() {
            addCriterion("onsale is not null");
            return this;
        }

        public Criteria andOnsaleEqualTo(Boolean value) {
            addCriterion("onsale =", value, "onsale");
            return this;
        }

        public Criteria andOnsaleNotEqualTo(Boolean value) {
            addCriterion("onsale <>", value, "onsale");
            return this;
        }

        public Criteria andOnsaleGreaterThan(Boolean value) {
            addCriterion("onsale >", value, "onsale");
            return this;
        }

        public Criteria andOnsaleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("onsale >=", value, "onsale");
            return this;
        }

        public Criteria andOnsaleLessThan(Boolean value) {
            addCriterion("onsale <", value, "onsale");
            return this;
        }

        public Criteria andOnsaleLessThanOrEqualTo(Boolean value) {
            addCriterion("onsale <=", value, "onsale");
            return this;
        }

        public Criteria andOnsaleIn(List<Boolean> values) {
            addCriterion("onsale in", values, "onsale");
            return this;
        }

        public Criteria andOnsaleNotIn(List<Boolean> values) {
            addCriterion("onsale not in", values, "onsale");
            return this;
        }

        public Criteria andOnsaleBetween(Boolean value1, Boolean value2) {
            addCriterion("onsale between", value1, value2, "onsale");
            return this;
        }

        public Criteria andOnsaleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("onsale not between", value1, value2, "onsale");
            return this;
        }

        public Criteria andMnIsNull() {
            addCriterion("MN is null");
            return this;
        }

        public Criteria andMnIsNotNull() {
            addCriterion("MN is not null");
            return this;
        }

        public Criteria andMnEqualTo(String value) {
            addCriterion("MN =", value, "mn");
            return this;
        }

        public Criteria andMnNotEqualTo(String value) {
            addCriterion("MN <>", value, "mn");
            return this;
        }

        public Criteria andMnGreaterThan(String value) {
            addCriterion("MN >", value, "mn");
            return this;
        }

        public Criteria andMnGreaterThanOrEqualTo(String value) {
            addCriterion("MN >=", value, "mn");
            return this;
        }

        public Criteria andMnLessThan(String value) {
            addCriterion("MN <", value, "mn");
            return this;
        }

        public Criteria andMnLessThanOrEqualTo(String value) {
            addCriterion("MN <=", value, "mn");
            return this;
        }

        public Criteria andMnLike(String value) {
            addCriterion("MN like", value, "mn");
            return this;
        }

        public Criteria andMnNotLike(String value) {
            addCriterion("MN not like", value, "mn");
            return this;
        }

        public Criteria andMnIn(List<String> values) {
            addCriterion("MN in", values, "mn");
            return this;
        }

        public Criteria andMnNotIn(List<String> values) {
            addCriterion("MN not in", values, "mn");
            return this;
        }

        public Criteria andMnBetween(String value1, String value2) {
            addCriterion("MN between", value1, value2, "mn");
            return this;
        }

        public Criteria andMnNotBetween(String value1, String value2) {
            addCriterion("MN not between", value1, value2, "mn");
            return this;
        }

        public Criteria andMmIsNull() {
            addCriterion("mm is null");
            return this;
        }

        public Criteria andMmIsNotNull() {
            addCriterion("mm is not null");
            return this;
        }

        public Criteria andMmEqualTo(String value) {
            addCriterion("mm =", value, "mm");
            return this;
        }

        public Criteria andMmNotEqualTo(String value) {
            addCriterion("mm <>", value, "mm");
            return this;
        }

        public Criteria andMmGreaterThan(String value) {
            addCriterion("mm >", value, "mm");
            return this;
        }

        public Criteria andMmGreaterThanOrEqualTo(String value) {
            addCriterion("mm >=", value, "mm");
            return this;
        }

        public Criteria andMmLessThan(String value) {
            addCriterion("mm <", value, "mm");
            return this;
        }

        public Criteria andMmLessThanOrEqualTo(String value) {
            addCriterion("mm <=", value, "mm");
            return this;
        }

        public Criteria andMmLike(String value) {
            addCriterion("mm like", value, "mm");
            return this;
        }

        public Criteria andMmNotLike(String value) {
            addCriterion("mm not like", value, "mm");
            return this;
        }

        public Criteria andMmIn(List<String> values) {
            addCriterion("mm in", values, "mm");
            return this;
        }

        public Criteria andMmNotIn(List<String> values) {
            addCriterion("mm not in", values, "mm");
            return this;
        }

        public Criteria andMmBetween(String value1, String value2) {
            addCriterion("mm between", value1, value2, "mm");
            return this;
        }

        public Criteria andMmNotBetween(String value1, String value2) {
            addCriterion("mm not between", value1, value2, "mm");
            return this;
        }

        public Criteria andLlIsNull() {
            addCriterion("LL is null");
            return this;
        }

        public Criteria andLlIsNotNull() {
            addCriterion("LL is not null");
            return this;
        }

        public Criteria andLlEqualTo(String value) {
            addCriterion("LL =", value, "ll");
            return this;
        }

        public Criteria andLlNotEqualTo(String value) {
            addCriterion("LL <>", value, "ll");
            return this;
        }

        public Criteria andLlGreaterThan(String value) {
            addCriterion("LL >", value, "ll");
            return this;
        }

        public Criteria andLlGreaterThanOrEqualTo(String value) {
            addCriterion("LL >=", value, "ll");
            return this;
        }

        public Criteria andLlLessThan(String value) {
            addCriterion("LL <", value, "ll");
            return this;
        }

        public Criteria andLlLessThanOrEqualTo(String value) {
            addCriterion("LL <=", value, "ll");
            return this;
        }

        public Criteria andLlLike(String value) {
            addCriterion("LL like", value, "ll");
            return this;
        }

        public Criteria andLlNotLike(String value) {
            addCriterion("LL not like", value, "ll");
            return this;
        }

        public Criteria andLlIn(List<String> values) {
            addCriterion("LL in", values, "ll");
            return this;
        }

        public Criteria andLlNotIn(List<String> values) {
            addCriterion("LL not in", values, "ll");
            return this;
        }

        public Criteria andLlBetween(String value1, String value2) {
            addCriterion("LL between", value1, value2, "ll");
            return this;
        }

        public Criteria andLlNotBetween(String value1, String value2) {
            addCriterion("LL not between", value1, value2, "ll");
            return this;
        }

        public Criteria andGuIsNull() {
            addCriterion("GU is null");
            return this;
        }

        public Criteria andGuIsNotNull() {
            addCriterion("GU is not null");
            return this;
        }

        public Criteria andGuEqualTo(String value) {
            addCriterion("GU =", value, "gu");
            return this;
        }

        public Criteria andGuNotEqualTo(String value) {
            addCriterion("GU <>", value, "gu");
            return this;
        }

        public Criteria andGuGreaterThan(String value) {
            addCriterion("GU >", value, "gu");
            return this;
        }

        public Criteria andGuGreaterThanOrEqualTo(String value) {
            addCriterion("GU >=", value, "gu");
            return this;
        }

        public Criteria andGuLessThan(String value) {
            addCriterion("GU <", value, "gu");
            return this;
        }

        public Criteria andGuLessThanOrEqualTo(String value) {
            addCriterion("GU <=", value, "gu");
            return this;
        }

        public Criteria andGuLike(String value) {
            addCriterion("GU like", value, "gu");
            return this;
        }

        public Criteria andGuNotLike(String value) {
            addCriterion("GU not like", value, "gu");
            return this;
        }

        public Criteria andGuIn(List<String> values) {
            addCriterion("GU in", values, "gu");
            return this;
        }

        public Criteria andGuNotIn(List<String> values) {
            addCriterion("GU not in", values, "gu");
            return this;
        }

        public Criteria andGuBetween(String value1, String value2) {
            addCriterion("GU between", value1, value2, "gu");
            return this;
        }

        public Criteria andGuNotBetween(String value1, String value2) {
            addCriterion("GU not between", value1, value2, "gu");
            return this;
        }

        public Criteria andC1IsNull() {
            addCriterion("c1 is null");
            return this;
        }

        public Criteria andC1IsNotNull() {
            addCriterion("c1 is not null");
            return this;
        }

        public Criteria andC1EqualTo(String value) {
            addCriterion("c1 =", value, "c1");
            return this;
        }

        public Criteria andC1NotEqualTo(String value) {
            addCriterion("c1 <>", value, "c1");
            return this;
        }

        public Criteria andC1GreaterThan(String value) {
            addCriterion("c1 >", value, "c1");
            return this;
        }

        public Criteria andC1GreaterThanOrEqualTo(String value) {
            addCriterion("c1 >=", value, "c1");
            return this;
        }

        public Criteria andC1LessThan(String value) {
            addCriterion("c1 <", value, "c1");
            return this;
        }

        public Criteria andC1LessThanOrEqualTo(String value) {
            addCriterion("c1 <=", value, "c1");
            return this;
        }

        public Criteria andC1Like(String value) {
            addCriterion("c1 like", value, "c1");
            return this;
        }

        public Criteria andC1NotLike(String value) {
            addCriterion("c1 not like", value, "c1");
            return this;
        }

        public Criteria andC1In(List<String> values) {
            addCriterion("c1 in", values, "c1");
            return this;
        }

        public Criteria andC1NotIn(List<String> values) {
            addCriterion("c1 not in", values, "c1");
            return this;
        }

        public Criteria andC1Between(String value1, String value2) {
            addCriterion("c1 between", value1, value2, "c1");
            return this;
        }

        public Criteria andC1NotBetween(String value1, String value2) {
            addCriterion("c1 not between", value1, value2, "c1");
            return this;
        }

        public Criteria andC2IsNull() {
            addCriterion("c2 is null");
            return this;
        }

        public Criteria andC2IsNotNull() {
            addCriterion("c2 is not null");
            return this;
        }

        public Criteria andC2EqualTo(String value) {
            addCriterion("c2 =", value, "c2");
            return this;
        }

        public Criteria andC2NotEqualTo(String value) {
            addCriterion("c2 <>", value, "c2");
            return this;
        }

        public Criteria andC2GreaterThan(String value) {
            addCriterion("c2 >", value, "c2");
            return this;
        }

        public Criteria andC2GreaterThanOrEqualTo(String value) {
            addCriterion("c2 >=", value, "c2");
            return this;
        }

        public Criteria andC2LessThan(String value) {
            addCriterion("c2 <", value, "c2");
            return this;
        }

        public Criteria andC2LessThanOrEqualTo(String value) {
            addCriterion("c2 <=", value, "c2");
            return this;
        }

        public Criteria andC2Like(String value) {
            addCriterion("c2 like", value, "c2");
            return this;
        }

        public Criteria andC2NotLike(String value) {
            addCriterion("c2 not like", value, "c2");
            return this;
        }

        public Criteria andC2In(List<String> values) {
            addCriterion("c2 in", values, "c2");
            return this;
        }

        public Criteria andC2NotIn(List<String> values) {
            addCriterion("c2 not in", values, "c2");
            return this;
        }

        public Criteria andC2Between(String value1, String value2) {
            addCriterion("c2 between", value1, value2, "c2");
            return this;
        }

        public Criteria andC2NotBetween(String value1, String value2) {
            addCriterion("c2 not between", value1, value2, "c2");
            return this;
        }

        public Criteria andBIsNull() {
            addCriterion("b is null");
            return this;
        }

        public Criteria andBIsNotNull() {
            addCriterion("b is not null");
            return this;
        }

        public Criteria andBEqualTo(String value) {
            addCriterion("b =", value, "b");
            return this;
        }

        public Criteria andBNotEqualTo(String value) {
            addCriterion("b <>", value, "b");
            return this;
        }

        public Criteria andBGreaterThan(String value) {
            addCriterion("b >", value, "b");
            return this;
        }

        public Criteria andBGreaterThanOrEqualTo(String value) {
            addCriterion("b >=", value, "b");
            return this;
        }

        public Criteria andBLessThan(String value) {
            addCriterion("b <", value, "b");
            return this;
        }

        public Criteria andBLessThanOrEqualTo(String value) {
            addCriterion("b <=", value, "b");
            return this;
        }

        public Criteria andBLike(String value) {
            addCriterion("b like", value, "b");
            return this;
        }

        public Criteria andBNotLike(String value) {
            addCriterion("b not like", value, "b");
            return this;
        }

        public Criteria andBIn(List<String> values) {
            addCriterion("b in", values, "b");
            return this;
        }

        public Criteria andBNotIn(List<String> values) {
            addCriterion("b not in", values, "b");
            return this;
        }

        public Criteria andBBetween(String value1, String value2) {
            addCriterion("b between", value1, value2, "b");
            return this;
        }

        public Criteria andBNotBetween(String value1, String value2) {
            addCriterion("b not between", value1, value2, "b");
            return this;
        }

        public Criteria andCIsNull() {
            addCriterion("c is null");
            return this;
        }

        public Criteria andCIsNotNull() {
            addCriterion("c is not null");
            return this;
        }

        public Criteria andCEqualTo(String value) {
            addCriterion("c =", value, "c");
            return this;
        }

        public Criteria andCNotEqualTo(String value) {
            addCriterion("c <>", value, "c");
            return this;
        }

        public Criteria andCGreaterThan(String value) {
            addCriterion("c >", value, "c");
            return this;
        }

        public Criteria andCGreaterThanOrEqualTo(String value) {
            addCriterion("c >=", value, "c");
            return this;
        }

        public Criteria andCLessThan(String value) {
            addCriterion("c <", value, "c");
            return this;
        }

        public Criteria andCLessThanOrEqualTo(String value) {
            addCriterion("c <=", value, "c");
            return this;
        }

        public Criteria andCLike(String value) {
            addCriterion("c like", value, "c");
            return this;
        }

        public Criteria andCNotLike(String value) {
            addCriterion("c not like", value, "c");
            return this;
        }

        public Criteria andCIn(List<String> values) {
            addCriterion("c in", values, "c");
            return this;
        }

        public Criteria andCNotIn(List<String> values) {
            addCriterion("c not in", values, "c");
            return this;
        }

        public Criteria andCBetween(String value1, String value2) {
            addCriterion("c between", value1, value2, "c");
            return this;
        }

        public Criteria andCNotBetween(String value1, String value2) {
            addCriterion("c not between", value1, value2, "c");
            return this;
        }

        public Criteria andYIsNull() {
            addCriterion("y is null");
            return this;
        }

        public Criteria andYIsNotNull() {
            addCriterion("y is not null");
            return this;
        }

        public Criteria andYEqualTo(String value) {
            addCriterion("y =", value, "y");
            return this;
        }

        public Criteria andYNotEqualTo(String value) {
            addCriterion("y <>", value, "y");
            return this;
        }

        public Criteria andYGreaterThan(String value) {
            addCriterion("y >", value, "y");
            return this;
        }

        public Criteria andYGreaterThanOrEqualTo(String value) {
            addCriterion("y >=", value, "y");
            return this;
        }

        public Criteria andYLessThan(String value) {
            addCriterion("y <", value, "y");
            return this;
        }

        public Criteria andYLessThanOrEqualTo(String value) {
            addCriterion("y <=", value, "y");
            return this;
        }

        public Criteria andYLike(String value) {
            addCriterion("y like", value, "y");
            return this;
        }

        public Criteria andYNotLike(String value) {
            addCriterion("y not like", value, "y");
            return this;
        }

        public Criteria andYIn(List<String> values) {
            addCriterion("y in", values, "y");
            return this;
        }

        public Criteria andYNotIn(List<String> values) {
            addCriterion("y not in", values, "y");
            return this;
        }

        public Criteria andYBetween(String value1, String value2) {
            addCriterion("y between", value1, value2, "y");
            return this;
        }

        public Criteria andYNotBetween(String value1, String value2) {
            addCriterion("y not between", value1, value2, "y");
            return this;
        }

        public Criteria andWhIsNull() {
            addCriterion("wh is null");
            return this;
        }

        public Criteria andWhIsNotNull() {
            addCriterion("wh is not null");
            return this;
        }

        public Criteria andWhEqualTo(String value) {
            addCriterion("wh =", value, "wh");
            return this;
        }

        public Criteria andWhNotEqualTo(String value) {
            addCriterion("wh <>", value, "wh");
            return this;
        }

        public Criteria andWhGreaterThan(String value) {
            addCriterion("wh >", value, "wh");
            return this;
        }

        public Criteria andWhGreaterThanOrEqualTo(String value) {
            addCriterion("wh >=", value, "wh");
            return this;
        }

        public Criteria andWhLessThan(String value) {
            addCriterion("wh <", value, "wh");
            return this;
        }

        public Criteria andWhLessThanOrEqualTo(String value) {
            addCriterion("wh <=", value, "wh");
            return this;
        }

        public Criteria andWhLike(String value) {
            addCriterion("wh like", value, "wh");
            return this;
        }

        public Criteria andWhNotLike(String value) {
            addCriterion("wh not like", value, "wh");
            return this;
        }

        public Criteria andWhIn(List<String> values) {
            addCriterion("wh in", values, "wh");
            return this;
        }

        public Criteria andWhNotIn(List<String> values) {
            addCriterion("wh not in", values, "wh");
            return this;
        }

        public Criteria andWhBetween(String value1, String value2) {
            addCriterion("wh between", value1, value2, "wh");
            return this;
        }

        public Criteria andWhNotBetween(String value1, String value2) {
            addCriterion("wh not between", value1, value2, "wh");
            return this;
        }

        public Criteria andOpIsNull() {
            addCriterion("Op is null");
            return this;
        }

        public Criteria andOpIsNotNull() {
            addCriterion("Op is not null");
            return this;
        }

        public Criteria andOpEqualTo(String value) {
            addCriterion("Op =", value, "op");
            return this;
        }

        public Criteria andOpNotEqualTo(String value) {
            addCriterion("Op <>", value, "op");
            return this;
        }

        public Criteria andOpGreaterThan(String value) {
            addCriterion("Op >", value, "op");
            return this;
        }

        public Criteria andOpGreaterThanOrEqualTo(String value) {
            addCriterion("Op >=", value, "op");
            return this;
        }

        public Criteria andOpLessThan(String value) {
            addCriterion("Op <", value, "op");
            return this;
        }

        public Criteria andOpLessThanOrEqualTo(String value) {
            addCriterion("Op <=", value, "op");
            return this;
        }

        public Criteria andOpLike(String value) {
            addCriterion("Op like", value, "op");
            return this;
        }

        public Criteria andOpNotLike(String value) {
            addCriterion("Op not like", value, "op");
            return this;
        }

        public Criteria andOpIn(List<String> values) {
            addCriterion("Op in", values, "op");
            return this;
        }

        public Criteria andOpNotIn(List<String> values) {
            addCriterion("Op not in", values, "op");
            return this;
        }

        public Criteria andOpBetween(String value1, String value2) {
            addCriterion("Op between", value1, value2, "op");
            return this;
        }

        public Criteria andOpNotBetween(String value1, String value2) {
            addCriterion("Op not between", value1, value2, "op");
            return this;
        }

        public Criteria andOtIsNull() {
            addCriterion("OT is null");
            return this;
        }

        public Criteria andOtIsNotNull() {
            addCriterion("OT is not null");
            return this;
        }

        public Criteria andOtEqualTo(String value) {
            addCriterion("OT =", value, "ot");
            return this;
        }

        public Criteria andOtNotEqualTo(String value) {
            addCriterion("OT <>", value, "ot");
            return this;
        }

        public Criteria andOtGreaterThan(String value) {
            addCriterion("OT >", value, "ot");
            return this;
        }

        public Criteria andOtGreaterThanOrEqualTo(String value) {
            addCriterion("OT >=", value, "ot");
            return this;
        }

        public Criteria andOtLessThan(String value) {
            addCriterion("OT <", value, "ot");
            return this;
        }

        public Criteria andOtLessThanOrEqualTo(String value) {
            addCriterion("OT <=", value, "ot");
            return this;
        }

        public Criteria andOtLike(String value) {
            addCriterion("OT like", value, "ot");
            return this;
        }

        public Criteria andOtNotLike(String value) {
            addCriterion("OT not like", value, "ot");
            return this;
        }

        public Criteria andOtIn(List<String> values) {
            addCriterion("OT in", values, "ot");
            return this;
        }

        public Criteria andOtNotIn(List<String> values) {
            addCriterion("OT not in", values, "ot");
            return this;
        }

        public Criteria andOtBetween(String value1, String value2) {
            addCriterion("OT between", value1, value2, "ot");
            return this;
        }

        public Criteria andOtNotBetween(String value1, String value2) {
            addCriterion("OT not between", value1, value2, "ot");
            return this;
        }

        public Criteria andOvIsNull() {
            addCriterion("oV is null");
            return this;
        }

        public Criteria andOvIsNotNull() {
            addCriterion("oV is not null");
            return this;
        }

        public Criteria andOvEqualTo(String value) {
            addCriterion("oV =", value, "ov");
            return this;
        }

        public Criteria andOvNotEqualTo(String value) {
            addCriterion("oV <>", value, "ov");
            return this;
        }

        public Criteria andOvGreaterThan(String value) {
            addCriterion("oV >", value, "ov");
            return this;
        }

        public Criteria andOvGreaterThanOrEqualTo(String value) {
            addCriterion("oV >=", value, "ov");
            return this;
        }

        public Criteria andOvLessThan(String value) {
            addCriterion("oV <", value, "ov");
            return this;
        }

        public Criteria andOvLessThanOrEqualTo(String value) {
            addCriterion("oV <=", value, "ov");
            return this;
        }

        public Criteria andOvLike(String value) {
            addCriterion("oV like", value, "ov");
            return this;
        }

        public Criteria andOvNotLike(String value) {
            addCriterion("oV not like", value, "ov");
            return this;
        }

        public Criteria andOvIn(List<String> values) {
            addCriterion("oV in", values, "ov");
            return this;
        }

        public Criteria andOvNotIn(List<String> values) {
            addCriterion("oV not in", values, "ov");
            return this;
        }

        public Criteria andOvBetween(String value1, String value2) {
            addCriterion("oV between", value1, value2, "ov");
            return this;
        }

        public Criteria andOvNotBetween(String value1, String value2) {
            addCriterion("oV not between", value1, value2, "ov");
            return this;
        }

        public Criteria andCpIsNull() {
            addCriterion("cp is null");
            return this;
        }

        public Criteria andCpIsNotNull() {
            addCriterion("cp is not null");
            return this;
        }

        public Criteria andCpEqualTo(String value) {
            addCriterion("cp =", value, "cp");
            return this;
        }

        public Criteria andCpNotEqualTo(String value) {
            addCriterion("cp <>", value, "cp");
            return this;
        }

        public Criteria andCpGreaterThan(String value) {
            addCriterion("cp >", value, "cp");
            return this;
        }

        public Criteria andCpGreaterThanOrEqualTo(String value) {
            addCriterion("cp >=", value, "cp");
            return this;
        }

        public Criteria andCpLessThan(String value) {
            addCriterion("cp <", value, "cp");
            return this;
        }

        public Criteria andCpLessThanOrEqualTo(String value) {
            addCriterion("cp <=", value, "cp");
            return this;
        }

        public Criteria andCpLike(String value) {
            addCriterion("cp like", value, "cp");
            return this;
        }

        public Criteria andCpNotLike(String value) {
            addCriterion("cp not like", value, "cp");
            return this;
        }

        public Criteria andCpIn(List<String> values) {
            addCriterion("cp in", values, "cp");
            return this;
        }

        public Criteria andCpNotIn(List<String> values) {
            addCriterion("cp not in", values, "cp");
            return this;
        }

        public Criteria andCpBetween(String value1, String value2) {
            addCriterion("cp between", value1, value2, "cp");
            return this;
        }

        public Criteria andCpNotBetween(String value1, String value2) {
            addCriterion("cp not between", value1, value2, "cp");
            return this;
        }

        public Criteria andHpIsNull() {
            addCriterion("hp is null");
            return this;
        }

        public Criteria andHpIsNotNull() {
            addCriterion("hp is not null");
            return this;
        }

        public Criteria andHpEqualTo(String value) {
            addCriterion("hp =", value, "hp");
            return this;
        }

        public Criteria andHpNotEqualTo(String value) {
            addCriterion("hp <>", value, "hp");
            return this;
        }

        public Criteria andHpGreaterThan(String value) {
            addCriterion("hp >", value, "hp");
            return this;
        }

        public Criteria andHpGreaterThanOrEqualTo(String value) {
            addCriterion("hp >=", value, "hp");
            return this;
        }

        public Criteria andHpLessThan(String value) {
            addCriterion("hp <", value, "hp");
            return this;
        }

        public Criteria andHpLessThanOrEqualTo(String value) {
            addCriterion("hp <=", value, "hp");
            return this;
        }

        public Criteria andHpLike(String value) {
            addCriterion("hp like", value, "hp");
            return this;
        }

        public Criteria andHpNotLike(String value) {
            addCriterion("hp not like", value, "hp");
            return this;
        }

        public Criteria andHpIn(List<String> values) {
            addCriterion("hp in", values, "hp");
            return this;
        }

        public Criteria andHpNotIn(List<String> values) {
            addCriterion("hp not in", values, "hp");
            return this;
        }

        public Criteria andHpBetween(String value1, String value2) {
            addCriterion("hp between", value1, value2, "hp");
            return this;
        }

        public Criteria andHpNotBetween(String value1, String value2) {
            addCriterion("hp not between", value1, value2, "hp");
            return this;
        }

        public Criteria andYpIsNull() {
            addCriterion("yp is null");
            return this;
        }

        public Criteria andYpIsNotNull() {
            addCriterion("yp is not null");
            return this;
        }

        public Criteria andYpEqualTo(String value) {
            addCriterion("yp =", value, "yp");
            return this;
        }

        public Criteria andYpNotEqualTo(String value) {
            addCriterion("yp <>", value, "yp");
            return this;
        }

        public Criteria andYpGreaterThan(String value) {
            addCriterion("yp >", value, "yp");
            return this;
        }

        public Criteria andYpGreaterThanOrEqualTo(String value) {
            addCriterion("yp >=", value, "yp");
            return this;
        }

        public Criteria andYpLessThan(String value) {
            addCriterion("yp <", value, "yp");
            return this;
        }

        public Criteria andYpLessThanOrEqualTo(String value) {
            addCriterion("yp <=", value, "yp");
            return this;
        }

        public Criteria andYpLike(String value) {
            addCriterion("yp like", value, "yp");
            return this;
        }

        public Criteria andYpNotLike(String value) {
            addCriterion("yp not like", value, "yp");
            return this;
        }

        public Criteria andYpIn(List<String> values) {
            addCriterion("yp in", values, "yp");
            return this;
        }

        public Criteria andYpNotIn(List<String> values) {
            addCriterion("yp not in", values, "yp");
            return this;
        }

        public Criteria andYpBetween(String value1, String value2) {
            addCriterion("yp between", value1, value2, "yp");
            return this;
        }

        public Criteria andYpNotBetween(String value1, String value2) {
            addCriterion("yp not between", value1, value2, "yp");
            return this;
        }

        public Criteria andCmIsNull() {
            addCriterion("cM is null");
            return this;
        }

        public Criteria andCmIsNotNull() {
            addCriterion("cM is not null");
            return this;
        }

        public Criteria andCmEqualTo(String value) {
            addCriterion("cM =", value, "cm");
            return this;
        }

        public Criteria andCmNotEqualTo(String value) {
            addCriterion("cM <>", value, "cm");
            return this;
        }

        public Criteria andCmGreaterThan(String value) {
            addCriterion("cM >", value, "cm");
            return this;
        }

        public Criteria andCmGreaterThanOrEqualTo(String value) {
            addCriterion("cM >=", value, "cm");
            return this;
        }

        public Criteria andCmLessThan(String value) {
            addCriterion("cM <", value, "cm");
            return this;
        }

        public Criteria andCmLessThanOrEqualTo(String value) {
            addCriterion("cM <=", value, "cm");
            return this;
        }

        public Criteria andCmLike(String value) {
            addCriterion("cM like", value, "cm");
            return this;
        }

        public Criteria andCmNotLike(String value) {
            addCriterion("cM not like", value, "cm");
            return this;
        }

        public Criteria andCmIn(List<String> values) {
            addCriterion("cM in", values, "cm");
            return this;
        }

        public Criteria andCmNotIn(List<String> values) {
            addCriterion("cM not in", values, "cm");
            return this;
        }

        public Criteria andCmBetween(String value1, String value2) {
            addCriterion("cM between", value1, value2, "cm");
            return this;
        }

        public Criteria andCmNotBetween(String value1, String value2) {
            addCriterion("cM not between", value1, value2, "cm");
            return this;
        }

        public Criteria andPtIsNull() {
            addCriterion("pT is null");
            return this;
        }

        public Criteria andPtIsNotNull() {
            addCriterion("pT is not null");
            return this;
        }

        public Criteria andPtEqualTo(String value) {
            addCriterion("pT =", value, "pt");
            return this;
        }

        public Criteria andPtNotEqualTo(String value) {
            addCriterion("pT <>", value, "pt");
            return this;
        }

        public Criteria andPtGreaterThan(String value) {
            addCriterion("pT >", value, "pt");
            return this;
        }

        public Criteria andPtGreaterThanOrEqualTo(String value) {
            addCriterion("pT >=", value, "pt");
            return this;
        }

        public Criteria andPtLessThan(String value) {
            addCriterion("pT <", value, "pt");
            return this;
        }

        public Criteria andPtLessThanOrEqualTo(String value) {
            addCriterion("pT <=", value, "pt");
            return this;
        }

        public Criteria andPtLike(String value) {
            addCriterion("pT like", value, "pt");
            return this;
        }

        public Criteria andPtNotLike(String value) {
            addCriterion("pT not like", value, "pt");
            return this;
        }

        public Criteria andPtIn(List<String> values) {
            addCriterion("pT in", values, "pt");
            return this;
        }

        public Criteria andPtNotIn(List<String> values) {
            addCriterion("pT not in", values, "pt");
            return this;
        }

        public Criteria andPtBetween(String value1, String value2) {
            addCriterion("pT between", value1, value2, "pt");
            return this;
        }

        public Criteria andPtNotBetween(String value1, String value2) {
            addCriterion("pT not between", value1, value2, "pt");
            return this;
        }

        public Criteria andCtIsNull() {
            addCriterion("cT is null");
            return this;
        }

        public Criteria andCtIsNotNull() {
            addCriterion("cT is not null");
            return this;
        }

        public Criteria andCtEqualTo(String value) {
            addCriterion("cT =", value, "ct");
            return this;
        }

        public Criteria andCtNotEqualTo(String value) {
            addCriterion("cT <>", value, "ct");
            return this;
        }

        public Criteria andCtGreaterThan(String value) {
            addCriterion("cT >", value, "ct");
            return this;
        }

        public Criteria andCtGreaterThanOrEqualTo(String value) {
            addCriterion("cT >=", value, "ct");
            return this;
        }

        public Criteria andCtLessThan(String value) {
            addCriterion("cT <", value, "ct");
            return this;
        }

        public Criteria andCtLessThanOrEqualTo(String value) {
            addCriterion("cT <=", value, "ct");
            return this;
        }

        public Criteria andCtLike(String value) {
            addCriterion("cT like", value, "ct");
            return this;
        }

        public Criteria andCtNotLike(String value) {
            addCriterion("cT not like", value, "ct");
            return this;
        }

        public Criteria andCtIn(List<String> values) {
            addCriterion("cT in", values, "ct");
            return this;
        }

        public Criteria andCtNotIn(List<String> values) {
            addCriterion("cT not in", values, "ct");
            return this;
        }

        public Criteria andCtBetween(String value1, String value2) {
            addCriterion("cT between", value1, value2, "ct");
            return this;
        }

        public Criteria andCtNotBetween(String value1, String value2) {
            addCriterion("cT not between", value1, value2, "ct");
            return this;
        }

        public Criteria andLoIsNull() {
            addCriterion("LO is null");
            return this;
        }

        public Criteria andLoIsNotNull() {
            addCriterion("LO is not null");
            return this;
        }

        public Criteria andLoEqualTo(String value) {
            addCriterion("LO =", value, "lo");
            return this;
        }

        public Criteria andLoNotEqualTo(String value) {
            addCriterion("LO <>", value, "lo");
            return this;
        }

        public Criteria andLoGreaterThan(String value) {
            addCriterion("LO >", value, "lo");
            return this;
        }

        public Criteria andLoGreaterThanOrEqualTo(String value) {
            addCriterion("LO >=", value, "lo");
            return this;
        }

        public Criteria andLoLessThan(String value) {
            addCriterion("LO <", value, "lo");
            return this;
        }

        public Criteria andLoLessThanOrEqualTo(String value) {
            addCriterion("LO <=", value, "lo");
            return this;
        }

        public Criteria andLoLike(String value) {
            addCriterion("LO like", value, "lo");
            return this;
        }

        public Criteria andLoNotLike(String value) {
            addCriterion("LO not like", value, "lo");
            return this;
        }

        public Criteria andLoIn(List<String> values) {
            addCriterion("LO in", values, "lo");
            return this;
        }

        public Criteria andLoNotIn(List<String> values) {
            addCriterion("LO not in", values, "lo");
            return this;
        }

        public Criteria andLoBetween(String value1, String value2) {
            addCriterion("LO between", value1, value2, "lo");
            return this;
        }

        public Criteria andLoNotBetween(String value1, String value2) {
            addCriterion("LO not between", value1, value2, "lo");
            return this;
        }

        public Criteria andLcIsNull() {
            addCriterion("LC is null");
            return this;
        }

        public Criteria andLcIsNotNull() {
            addCriterion("LC is not null");
            return this;
        }

        public Criteria andLcEqualTo(String value) {
            addCriterion("LC =", value, "lc");
            return this;
        }

        public Criteria andLcNotEqualTo(String value) {
            addCriterion("LC <>", value, "lc");
            return this;
        }

        public Criteria andLcGreaterThan(String value) {
            addCriterion("LC >", value, "lc");
            return this;
        }

        public Criteria andLcGreaterThanOrEqualTo(String value) {
            addCriterion("LC >=", value, "lc");
            return this;
        }

        public Criteria andLcLessThan(String value) {
            addCriterion("LC <", value, "lc");
            return this;
        }

        public Criteria andLcLessThanOrEqualTo(String value) {
            addCriterion("LC <=", value, "lc");
            return this;
        }

        public Criteria andLcLike(String value) {
            addCriterion("LC like", value, "lc");
            return this;
        }

        public Criteria andLcNotLike(String value) {
            addCriterion("LC not like", value, "lc");
            return this;
        }

        public Criteria andLcIn(List<String> values) {
            addCriterion("LC in", values, "lc");
            return this;
        }

        public Criteria andLcNotIn(List<String> values) {
            addCriterion("LC not in", values, "lc");
            return this;
        }

        public Criteria andLcBetween(String value1, String value2) {
            addCriterion("LC between", value1, value2, "lc");
            return this;
        }

        public Criteria andLcNotBetween(String value1, String value2) {
            addCriterion("LC not between", value1, value2, "lc");
            return this;
        }

        public Criteria andFuIsNull() {
            addCriterion("FU is null");
            return this;
        }

        public Criteria andFuIsNotNull() {
            addCriterion("FU is not null");
            return this;
        }

        public Criteria andFuEqualTo(String value) {
            addCriterion("FU =", value, "fu");
            return this;
        }

        public Criteria andFuNotEqualTo(String value) {
            addCriterion("FU <>", value, "fu");
            return this;
        }

        public Criteria andFuGreaterThan(String value) {
            addCriterion("FU >", value, "fu");
            return this;
        }

        public Criteria andFuGreaterThanOrEqualTo(String value) {
            addCriterion("FU >=", value, "fu");
            return this;
        }

        public Criteria andFuLessThan(String value) {
            addCriterion("FU <", value, "fu");
            return this;
        }

        public Criteria andFuLessThanOrEqualTo(String value) {
            addCriterion("FU <=", value, "fu");
            return this;
        }

        public Criteria andFuLike(String value) {
            addCriterion("FU like", value, "fu");
            return this;
        }

        public Criteria andFuNotLike(String value) {
            addCriterion("FU not like", value, "fu");
            return this;
        }

        public Criteria andFuIn(List<String> values) {
            addCriterion("FU in", values, "fu");
            return this;
        }

        public Criteria andFuNotIn(List<String> values) {
            addCriterion("FU not in", values, "fu");
            return this;
        }

        public Criteria andFuBetween(String value1, String value2) {
            addCriterion("FU between", value1, value2, "fu");
            return this;
        }

        public Criteria andFuNotBetween(String value1, String value2) {
            addCriterion("FU not between", value1, value2, "fu");
            return this;
        }

        public Criteria andYuIsNull() {
            addCriterion("YU is null");
            return this;
        }

        public Criteria andYuIsNotNull() {
            addCriterion("YU is not null");
            return this;
        }

        public Criteria andYuEqualTo(String value) {
            addCriterion("YU =", value, "yu");
            return this;
        }

        public Criteria andYuNotEqualTo(String value) {
            addCriterion("YU <>", value, "yu");
            return this;
        }

        public Criteria andYuGreaterThan(String value) {
            addCriterion("YU >", value, "yu");
            return this;
        }

        public Criteria andYuGreaterThanOrEqualTo(String value) {
            addCriterion("YU >=", value, "yu");
            return this;
        }

        public Criteria andYuLessThan(String value) {
            addCriterion("YU <", value, "yu");
            return this;
        }

        public Criteria andYuLessThanOrEqualTo(String value) {
            addCriterion("YU <=", value, "yu");
            return this;
        }

        public Criteria andYuLike(String value) {
            addCriterion("YU like", value, "yu");
            return this;
        }

        public Criteria andYuNotLike(String value) {
            addCriterion("YU not like", value, "yu");
            return this;
        }

        public Criteria andYuIn(List<String> values) {
            addCriterion("YU in", values, "yu");
            return this;
        }

        public Criteria andYuNotIn(List<String> values) {
            addCriterion("YU not in", values, "yu");
            return this;
        }

        public Criteria andYuBetween(String value1, String value2) {
            addCriterion("YU between", value1, value2, "yu");
            return this;
        }

        public Criteria andYuNotBetween(String value1, String value2) {
            addCriterion("YU not between", value1, value2, "yu");
            return this;
        }

        public Criteria andTlIsNull() {
            addCriterion("tl is null");
            return this;
        }

        public Criteria andTlIsNotNull() {
            addCriterion("tl is not null");
            return this;
        }

        public Criteria andTlEqualTo(String value) {
            addCriterion("tl =", value, "tl");
            return this;
        }

        public Criteria andTlNotEqualTo(String value) {
            addCriterion("tl <>", value, "tl");
            return this;
        }

        public Criteria andTlGreaterThan(String value) {
            addCriterion("tl >", value, "tl");
            return this;
        }

        public Criteria andTlGreaterThanOrEqualTo(String value) {
            addCriterion("tl >=", value, "tl");
            return this;
        }

        public Criteria andTlLessThan(String value) {
            addCriterion("tl <", value, "tl");
            return this;
        }

        public Criteria andTlLessThanOrEqualTo(String value) {
            addCriterion("tl <=", value, "tl");
            return this;
        }

        public Criteria andTlLike(String value) {
            addCriterion("tl like", value, "tl");
            return this;
        }

        public Criteria andTlNotLike(String value) {
            addCriterion("tl not like", value, "tl");
            return this;
        }

        public Criteria andTlIn(List<String> values) {
            addCriterion("tl in", values, "tl");
            return this;
        }

        public Criteria andTlNotIn(List<String> values) {
            addCriterion("tl not in", values, "tl");
            return this;
        }

        public Criteria andTlBetween(String value1, String value2) {
            addCriterion("tl between", value1, value2, "tl");
            return this;
        }

        public Criteria andTlNotBetween(String value1, String value2) {
            addCriterion("tl not between", value1, value2, "tl");
            return this;
        }
    }
}