package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;

public class PersonrelKey extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personrel.orgno
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String orgno;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personrel.pId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String pid;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personrel.orgno
     *
     * @return the value of personrel.orgno
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personrel.orgno
     *
     * @param orgno the value for personrel.orgno
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personrel.pId
     *
     * @return the value of personrel.pId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personrel.pId
     *
     * @param pid the value for personrel.pId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }
}