package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;

public class Personalinfo extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.pId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String pid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.pname
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String pname;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.orgno
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String orgno;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.orgname
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String orgname;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.telephone
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String telephone;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.roleId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String roleid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.status
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private Boolean status;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.pwd
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String pwd;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.usermax
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private Integer usermax;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.parentId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String parentid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column personalinfo.ramark
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private String ramark;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.pId
     *
     * @return the value of personalinfo.pId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.pId
     *
     * @param pid the value for personalinfo.pId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.pname
     *
     * @return the value of personalinfo.pname
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.pname
     *
     * @param pname the value for personalinfo.pname
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.orgno
     *
     * @return the value of personalinfo.orgno
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.orgno
     *
     * @param orgno the value for personalinfo.orgno
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.orgname
     *
     * @return the value of personalinfo.orgname
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.orgname
     *
     * @param orgname the value for personalinfo.orgname
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.telephone
     *
     * @return the value of personalinfo.telephone
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.telephone
     *
     * @param telephone the value for personalinfo.telephone
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.roleId
     *
     * @return the value of personalinfo.roleId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.roleId
     *
     * @param roleid the value for personalinfo.roleId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.status
     *
     * @return the value of personalinfo.status
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.status
     *
     * @param status the value for personalinfo.status
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.pwd
     *
     * @return the value of personalinfo.pwd
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.pwd
     *
     * @param pwd the value for personalinfo.pwd
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.usermax
     *
     * @return the value of personalinfo.usermax
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public Integer getUsermax() {
        return usermax;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.usermax
     *
     * @param usermax the value for personalinfo.usermax
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setUsermax(Integer usermax) {
        this.usermax = usermax;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.parentId
     *
     * @return the value of personalinfo.parentId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.parentId
     *
     * @param parentid the value for personalinfo.parentId
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column personalinfo.ramark
     *
     * @return the value of personalinfo.ramark
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getRamark() {
        return ramark;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column personalinfo.ramark
     *
     * @param ramark the value for personalinfo.ramark
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setRamark(String ramark) {
        this.ramark = ramark;
    }
}