package com.pinelet.utp.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PersonalinfoExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public PersonalinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    protected PersonalinfoExample(PersonalinfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPidIsNull() {
            addCriterion("pId is null");
            return this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pId is not null");
            return this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pId =", value, "pid");
            return this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pId <>", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pId >", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pId >=", value, "pid");
            return this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pId <", value, "pid");
            return this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pId <=", value, "pid");
            return this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pId like", value, "pid");
            return this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pId not like", value, "pid");
            return this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pId in", values, "pid");
            return this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pId not in", values, "pid");
            return this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pId between", value1, value2, "pid");
            return this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pId not between", value1, value2, "pid");
            return this;
        }

        public Criteria andPnameIsNull() {
            addCriterion("pname is null");
            return this;
        }

        public Criteria andPnameIsNotNull() {
            addCriterion("pname is not null");
            return this;
        }

        public Criteria andPnameEqualTo(String value) {
            addCriterion("pname =", value, "pname");
            return this;
        }

        public Criteria andPnameNotEqualTo(String value) {
            addCriterion("pname <>", value, "pname");
            return this;
        }

        public Criteria andPnameGreaterThan(String value) {
            addCriterion("pname >", value, "pname");
            return this;
        }

        public Criteria andPnameGreaterThanOrEqualTo(String value) {
            addCriterion("pname >=", value, "pname");
            return this;
        }

        public Criteria andPnameLessThan(String value) {
            addCriterion("pname <", value, "pname");
            return this;
        }

        public Criteria andPnameLessThanOrEqualTo(String value) {
            addCriterion("pname <=", value, "pname");
            return this;
        }

        public Criteria andPnameLike(String value) {
            addCriterion("pname like", value, "pname");
            return this;
        }

        public Criteria andPnameNotLike(String value) {
            addCriterion("pname not like", value, "pname");
            return this;
        }

        public Criteria andPnameIn(List<String> values) {
            addCriterion("pname in", values, "pname");
            return this;
        }

        public Criteria andPnameNotIn(List<String> values) {
            addCriterion("pname not in", values, "pname");
            return this;
        }

        public Criteria andPnameBetween(String value1, String value2) {
            addCriterion("pname between", value1, value2, "pname");
            return this;
        }

        public Criteria andPnameNotBetween(String value1, String value2) {
            addCriterion("pname not between", value1, value2, "pname");
            return this;
        }

        public Criteria andOrgnoIsNull() {
            addCriterion("orgno is null");
            return this;
        }

        public Criteria andOrgnoIsNotNull() {
            addCriterion("orgno is not null");
            return this;
        }

        public Criteria andOrgnoEqualTo(String value) {
            addCriterion("orgno =", value, "orgno");
            return this;
        }

        public Criteria andOrgnoNotEqualTo(String value) {
            addCriterion("orgno <>", value, "orgno");
            return this;
        }

        public Criteria andOrgnoGreaterThan(String value) {
            addCriterion("orgno >", value, "orgno");
            return this;
        }

        public Criteria andOrgnoGreaterThanOrEqualTo(String value) {
            addCriterion("orgno >=", value, "orgno");
            return this;
        }

        public Criteria andOrgnoLessThan(String value) {
            addCriterion("orgno <", value, "orgno");
            return this;
        }

        public Criteria andOrgnoLessThanOrEqualTo(String value) {
            addCriterion("orgno <=", value, "orgno");
            return this;
        }

        public Criteria andOrgnoLike(String value) {
            addCriterion("orgno like", value, "orgno");
            return this;
        }

        public Criteria andOrgnoNotLike(String value) {
            addCriterion("orgno not like", value, "orgno");
            return this;
        }

        public Criteria andOrgnoIn(List<String> values) {
            addCriterion("orgno in", values, "orgno");
            return this;
        }

        public Criteria andOrgnoNotIn(List<String> values) {
            addCriterion("orgno not in", values, "orgno");
            return this;
        }

        public Criteria andOrgnoBetween(String value1, String value2) {
            addCriterion("orgno between", value1, value2, "orgno");
            return this;
        }

        public Criteria andOrgnoNotBetween(String value1, String value2) {
            addCriterion("orgno not between", value1, value2, "orgno");
            return this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("orgname is null");
            return this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("orgname is not null");
            return this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("orgname =", value, "orgname");
            return this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("orgname <>", value, "orgname");
            return this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("orgname >", value, "orgname");
            return this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("orgname >=", value, "orgname");
            return this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("orgname <", value, "orgname");
            return this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("orgname <=", value, "orgname");
            return this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("orgname like", value, "orgname");
            return this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("orgname not like", value, "orgname");
            return this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("orgname in", values, "orgname");
            return this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("orgname not in", values, "orgname");
            return this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("orgname between", value1, value2, "orgname");
            return this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("orgname not between", value1, value2, "orgname");
            return this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("telephone =", value, "telephone");
            return this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("telephone <>", value, "telephone");
            return this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("telephone >", value, "telephone");
            return this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("telephone >=", value, "telephone");
            return this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("telephone <", value, "telephone");
            return this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("telephone <=", value, "telephone");
            return this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("telephone not like", value, "telephone");
            return this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("telephone in", values, "telephone");
            return this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("telephone not in", values, "telephone");
            return this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("roleId is null");
            return this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("roleId is not null");
            return this;
        }

        public Criteria andRoleidEqualTo(String value) {
            addCriterion("roleId =", value, "roleid");
            return this;
        }

        public Criteria andRoleidNotEqualTo(String value) {
            addCriterion("roleId <>", value, "roleid");
            return this;
        }

        public Criteria andRoleidGreaterThan(String value) {
            addCriterion("roleId >", value, "roleid");
            return this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(String value) {
            addCriterion("roleId >=", value, "roleid");
            return this;
        }

        public Criteria andRoleidLessThan(String value) {
            addCriterion("roleId <", value, "roleid");
            return this;
        }

        public Criteria andRoleidLessThanOrEqualTo(String value) {
            addCriterion("roleId <=", value, "roleid");
            return this;
        }

        public Criteria andRoleidLike(String value) {
            addCriterion("roleId like", value, "roleid");
            return this;
        }

        public Criteria andRoleidNotLike(String value) {
            addCriterion("roleId not like", value, "roleid");
            return this;
        }

        public Criteria andRoleidIn(List<String> values) {
            addCriterion("roleId in", values, "roleid");
            return this;
        }

        public Criteria andRoleidNotIn(List<String> values) {
            addCriterion("roleId not in", values, "roleid");
            return this;
        }

        public Criteria andRoleidBetween(String value1, String value2) {
            addCriterion("roleId between", value1, value2, "roleid");
            return this;
        }

        public Criteria andRoleidNotBetween(String value1, String value2) {
            addCriterion("roleId not between", value1, value2, "roleid");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return this;
        }

        public Criteria andUsermaxIsNull() {
            addCriterion("usermax is null");
            return this;
        }

        public Criteria andUsermaxIsNotNull() {
            addCriterion("usermax is not null");
            return this;
        }

        public Criteria andUsermaxEqualTo(Integer value) {
            addCriterion("usermax =", value, "usermax");
            return this;
        }

        public Criteria andUsermaxNotEqualTo(Integer value) {
            addCriterion("usermax <>", value, "usermax");
            return this;
        }

        public Criteria andUsermaxGreaterThan(Integer value) {
            addCriterion("usermax >", value, "usermax");
            return this;
        }

        public Criteria andUsermaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("usermax >=", value, "usermax");
            return this;
        }

        public Criteria andUsermaxLessThan(Integer value) {
            addCriterion("usermax <", value, "usermax");
            return this;
        }

        public Criteria andUsermaxLessThanOrEqualTo(Integer value) {
            addCriterion("usermax <=", value, "usermax");
            return this;
        }

        public Criteria andUsermaxIn(List<Integer> values) {
            addCriterion("usermax in", values, "usermax");
            return this;
        }

        public Criteria andUsermaxNotIn(List<Integer> values) {
            addCriterion("usermax not in", values, "usermax");
            return this;
        }

        public Criteria andUsermaxBetween(Integer value1, Integer value2) {
            addCriterion("usermax between", value1, value2, "usermax");
            return this;
        }

        public Criteria andUsermaxNotBetween(Integer value1, Integer value2) {
            addCriterion("usermax not between", value1, value2, "usermax");
            return this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("parentId is null");
            return this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("parentId is not null");
            return this;
        }

        public Criteria andParentidEqualTo(String value) {
            addCriterion("parentId =", value, "parentid");
            return this;
        }

        public Criteria andParentidNotEqualTo(String value) {
            addCriterion("parentId <>", value, "parentid");
            return this;
        }

        public Criteria andParentidGreaterThan(String value) {
            addCriterion("parentId >", value, "parentid");
            return this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(String value) {
            addCriterion("parentId >=", value, "parentid");
            return this;
        }

        public Criteria andParentidLessThan(String value) {
            addCriterion("parentId <", value, "parentid");
            return this;
        }

        public Criteria andParentidLessThanOrEqualTo(String value) {
            addCriterion("parentId <=", value, "parentid");
            return this;
        }

        public Criteria andParentidLike(String value) {
            addCriterion("parentId like", value, "parentid");
            return this;
        }

        public Criteria andParentidNotLike(String value) {
            addCriterion("parentId not like", value, "parentid");
            return this;
        }

        public Criteria andParentidIn(List<String> values) {
            addCriterion("parentId in", values, "parentid");
            return this;
        }

        public Criteria andParentidNotIn(List<String> values) {
            addCriterion("parentId not in", values, "parentid");
            return this;
        }

        public Criteria andParentidBetween(String value1, String value2) {
            addCriterion("parentId between", value1, value2, "parentid");
            return this;
        }

        public Criteria andParentidNotBetween(String value1, String value2) {
            addCriterion("parentId not between", value1, value2, "parentid");
            return this;
        }

        public Criteria andRamarkIsNull() {
            addCriterion("ramark is null");
            return this;
        }

        public Criteria andRamarkIsNotNull() {
            addCriterion("ramark is not null");
            return this;
        }

        public Criteria andRamarkEqualTo(String value) {
            addCriterion("ramark =", value, "ramark");
            return this;
        }

        public Criteria andRamarkNotEqualTo(String value) {
            addCriterion("ramark <>", value, "ramark");
            return this;
        }

        public Criteria andRamarkGreaterThan(String value) {
            addCriterion("ramark >", value, "ramark");
            return this;
        }

        public Criteria andRamarkGreaterThanOrEqualTo(String value) {
            addCriterion("ramark >=", value, "ramark");
            return this;
        }

        public Criteria andRamarkLessThan(String value) {
            addCriterion("ramark <", value, "ramark");
            return this;
        }

        public Criteria andRamarkLessThanOrEqualTo(String value) {
            addCriterion("ramark <=", value, "ramark");
            return this;
        }

        public Criteria andRamarkLike(String value) {
            addCriterion("ramark like", value, "ramark");
            return this;
        }

        public Criteria andRamarkNotLike(String value) {
            addCriterion("ramark not like", value, "ramark");
            return this;
        }

        public Criteria andRamarkIn(List<String> values) {
            addCriterion("ramark in", values, "ramark");
            return this;
        }

        public Criteria andRamarkNotIn(List<String> values) {
            addCriterion("ramark not in", values, "ramark");
            return this;
        }

        public Criteria andRamarkBetween(String value1, String value2) {
            addCriterion("ramark between", value1, value2, "ramark");
            return this;
        }

        public Criteria andRamarkNotBetween(String value1, String value2) {
            addCriterion("ramark not between", value1, value2, "ramark");
            return this;
        }
    }
}