package com.pinelet.utp.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TransinfoExample {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public TransinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected TransinfoExample(TransinfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andTransidIsNull() {
            addCriterion("transId is null");
            return this;
        }

        public Criteria andTransidIsNotNull() {
            addCriterion("transId is not null");
            return this;
        }

        public Criteria andTransidEqualTo(String value) {
            addCriterion("transId =", value, "transid");
            return this;
        }

        public Criteria andTransidNotEqualTo(String value) {
            addCriterion("transId <>", value, "transid");
            return this;
        }

        public Criteria andTransidGreaterThan(String value) {
            addCriterion("transId >", value, "transid");
            return this;
        }

        public Criteria andTransidGreaterThanOrEqualTo(String value) {
            addCriterion("transId >=", value, "transid");
            return this;
        }

        public Criteria andTransidLessThan(String value) {
            addCriterion("transId <", value, "transid");
            return this;
        }

        public Criteria andTransidLessThanOrEqualTo(String value) {
            addCriterion("transId <=", value, "transid");
            return this;
        }

        public Criteria andTransidLike(String value) {
            addCriterion("transId like", value, "transid");
            return this;
        }

        public Criteria andTransidNotLike(String value) {
            addCriterion("transId not like", value, "transid");
            return this;
        }

        public Criteria andTransidIn(List<String> values) {
            addCriterion("transId in", values, "transid");
            return this;
        }

        public Criteria andTransidNotIn(List<String> values) {
            addCriterion("transId not in", values, "transid");
            return this;
        }

        public Criteria andTransidBetween(String value1, String value2) {
            addCriterion("transId between", value1, value2, "transid");
            return this;
        }

        public Criteria andTransidNotBetween(String value1, String value2) {
            addCriterion("transId not between", value1, value2, "transid");
            return this;
        }

        public Criteria andCardcodeIsNull() {
            addCriterion("cardcode is null");
            return this;
        }

        public Criteria andCardcodeIsNotNull() {
            addCriterion("cardcode is not null");
            return this;
        }

        public Criteria andCardcodeEqualTo(String value) {
            addCriterion("cardcode =", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotEqualTo(String value) {
            addCriterion("cardcode <>", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeGreaterThan(String value) {
            addCriterion("cardcode >", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeGreaterThanOrEqualTo(String value) {
            addCriterion("cardcode >=", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLessThan(String value) {
            addCriterion("cardcode <", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLessThanOrEqualTo(String value) {
            addCriterion("cardcode <=", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeLike(String value) {
            addCriterion("cardcode like", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotLike(String value) {
            addCriterion("cardcode not like", value, "cardcode");
            return this;
        }

        public Criteria andCardcodeIn(List<String> values) {
            addCriterion("cardcode in", values, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotIn(List<String> values) {
            addCriterion("cardcode not in", values, "cardcode");
            return this;
        }

        public Criteria andCardcodeBetween(String value1, String value2) {
            addCriterion("cardcode between", value1, value2, "cardcode");
            return this;
        }

        public Criteria andCardcodeNotBetween(String value1, String value2) {
            addCriterion("cardcode not between", value1, value2, "cardcode");
            return this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pId is null");
            return this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pId is not null");
            return this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pId =", value, "pid");
            return this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pId <>", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pId >", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pId >=", value, "pid");
            return this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pId <", value, "pid");
            return this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pId <=", value, "pid");
            return this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pId like", value, "pid");
            return this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pId not like", value, "pid");
            return this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pId in", values, "pid");
            return this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pId not in", values, "pid");
            return this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pId between", value1, value2, "pid");
            return this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pId not between", value1, value2, "pid");
            return this;
        }

        public Criteria andGprscodeIsNull() {
            addCriterion("GPRSCode is null");
            return this;
        }

        public Criteria andGprscodeIsNotNull() {
            addCriterion("GPRSCode is not null");
            return this;
        }

        public Criteria andGprscodeEqualTo(String value) {
            addCriterion("GPRSCode =", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotEqualTo(String value) {
            addCriterion("GPRSCode <>", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThan(String value) {
            addCriterion("GPRSCode >", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeGreaterThanOrEqualTo(String value) {
            addCriterion("GPRSCode >=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThan(String value) {
            addCriterion("GPRSCode <", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLessThanOrEqualTo(String value) {
            addCriterion("GPRSCode <=", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeLike(String value) {
            addCriterion("GPRSCode like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotLike(String value) {
            addCriterion("GPRSCode not like", value, "gprscode");
            return this;
        }

        public Criteria andGprscodeIn(List<String> values) {
            addCriterion("GPRSCode in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotIn(List<String> values) {
            addCriterion("GPRSCode not in", values, "gprscode");
            return this;
        }

        public Criteria andGprscodeBetween(String value1, String value2) {
            addCriterion("GPRSCode between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andGprscodeNotBetween(String value1, String value2) {
            addCriterion("GPRSCode not between", value1, value2, "gprscode");
            return this;
        }

        public Criteria andTranstypeIsNull() {
            addCriterion("transtype is null");
            return this;
        }

        public Criteria andTranstypeIsNotNull() {
            addCriterion("transtype is not null");
            return this;
        }

        public Criteria andTranstypeEqualTo(String value) {
            addCriterion("transtype =", value, "transtype");
            return this;
        }

        public Criteria andTranstypeNotEqualTo(String value) {
            addCriterion("transtype <>", value, "transtype");
            return this;
        }

        public Criteria andTranstypeGreaterThan(String value) {
            addCriterion("transtype >", value, "transtype");
            return this;
        }

        public Criteria andTranstypeGreaterThanOrEqualTo(String value) {
            addCriterion("transtype >=", value, "transtype");
            return this;
        }

        public Criteria andTranstypeLessThan(String value) {
            addCriterion("transtype <", value, "transtype");
            return this;
        }

        public Criteria andTranstypeLessThanOrEqualTo(String value) {
            addCriterion("transtype <=", value, "transtype");
            return this;
        }

        public Criteria andTranstypeLike(String value) {
            addCriterion("transtype like", value, "transtype");
            return this;
        }

        public Criteria andTranstypeNotLike(String value) {
            addCriterion("transtype not like", value, "transtype");
            return this;
        }

        public Criteria andTranstypeIn(List<String> values) {
            addCriterion("transtype in", values, "transtype");
            return this;
        }

        public Criteria andTranstypeNotIn(List<String> values) {
            addCriterion("transtype not in", values, "transtype");
            return this;
        }

        public Criteria andTranstypeBetween(String value1, String value2) {
            addCriterion("transtype between", value1, value2, "transtype");
            return this;
        }

        public Criteria andTranstypeNotBetween(String value1, String value2) {
            addCriterion("transtype not between", value1, value2, "transtype");
            return this;
        }

        public Criteria andExpenditureIsNull() {
            addCriterion("expenditure is null");
            return this;
        }

        public Criteria andExpenditureIsNotNull() {
            addCriterion("expenditure is not null");
            return this;
        }

        public Criteria andExpenditureEqualTo(BigDecimal value) {
            addCriterion("expenditure =", value, "expenditure");
            return this;
        }

        public Criteria andExpenditureNotEqualTo(BigDecimal value) {
            addCriterion("expenditure <>", value, "expenditure");
            return this;
        }

        public Criteria andExpenditureGreaterThan(BigDecimal value) {
            addCriterion("expenditure >", value, "expenditure");
            return this;
        }

        public Criteria andExpenditureGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("expenditure >=", value, "expenditure");
            return this;
        }

        public Criteria andExpenditureLessThan(BigDecimal value) {
            addCriterion("expenditure <", value, "expenditure");
            return this;
        }

        public Criteria andExpenditureLessThanOrEqualTo(BigDecimal value) {
            addCriterion("expenditure <=", value, "expenditure");
            return this;
        }

        public Criteria andExpenditureIn(List<BigDecimal> values) {
            addCriterion("expenditure in", values, "expenditure");
            return this;
        }

        public Criteria andExpenditureNotIn(List<BigDecimal> values) {
            addCriterion("expenditure not in", values, "expenditure");
            return this;
        }

        public Criteria andExpenditureBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expenditure between", value1, value2, "expenditure");
            return this;
        }

        public Criteria andExpenditureNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expenditure not between", value1, value2, "expenditure");
            return this;
        }

        public Criteria andCardbalanceIsNull() {
            addCriterion("cardbalance is null");
            return this;
        }

        public Criteria andCardbalanceIsNotNull() {
            addCriterion("cardbalance is not null");
            return this;
        }

        public Criteria andCardbalanceEqualTo(BigDecimal value) {
            addCriterion("cardbalance =", value, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceNotEqualTo(BigDecimal value) {
            addCriterion("cardbalance <>", value, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceGreaterThan(BigDecimal value) {
            addCriterion("cardbalance >", value, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cardbalance >=", value, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceLessThan(BigDecimal value) {
            addCriterion("cardbalance <", value, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cardbalance <=", value, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceIn(List<BigDecimal> values) {
            addCriterion("cardbalance in", values, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceNotIn(List<BigDecimal> values) {
            addCriterion("cardbalance not in", values, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cardbalance between", value1, value2, "cardbalance");
            return this;
        }

        public Criteria andCardbalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cardbalance not between", value1, value2, "cardbalance");
            return this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return this;
        }

        public Criteria andTransdateIsNull() {
            addCriterion("transdate is null");
            return this;
        }

        public Criteria andTransdateIsNotNull() {
            addCriterion("transdate is not null");
            return this;
        }

        public Criteria andTransdateEqualTo(String value) {
            addCriterion("transdate =", value, "transdate");
            return this;
        }

        public Criteria andTransdateNotEqualTo(String value) {
            addCriterion("transdate <>", value, "transdate");
            return this;
        }

        public Criteria andTransdateGreaterThan(String value) {
            addCriterion("transdate >", value, "transdate");
            return this;
        }

        public Criteria andTransdateGreaterThanOrEqualTo(String value) {
            addCriterion("transdate >=", value, "transdate");
            return this;
        }

        public Criteria andTransdateLessThan(String value) {
            addCriterion("transdate <", value, "transdate");
            return this;
        }

        public Criteria andTransdateLessThanOrEqualTo(String value) {
            addCriterion("transdate <=", value, "transdate");
            return this;
        }

        public Criteria andTransdateLike(String value) {
            addCriterion("transdate like", value, "transdate");
            return this;
        }

        public Criteria andTransdateNotLike(String value) {
            addCriterion("transdate not like", value, "transdate");
            return this;
        }

        public Criteria andTransdateIn(List<String> values) {
            addCriterion("transdate in", values, "transdate");
            return this;
        }

        public Criteria andTransdateNotIn(List<String> values) {
            addCriterion("transdate not in", values, "transdate");
            return this;
        }

        public Criteria andTransdateBetween(String value1, String value2) {
            addCriterion("transdate between", value1, value2, "transdate");
            return this;
        }

        public Criteria andTransdateNotBetween(String value1, String value2) {
            addCriterion("transdate not between", value1, value2, "transdate");
            return this;
        }
    }
}