package com.pinelet.utp.entity;

import com.pinelet.utp.manage.form.ModelImpl;
import java.math.BigDecimal;

public class Transinfo extends ModelImpl {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.transId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String transid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.cardcode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String cardcode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.pId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String pid;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.GPRSCode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String gprscode;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.transtype
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String transtype;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.expenditure
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private BigDecimal expenditure;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.cardbalance
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private BigDecimal cardbalance;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.version
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String version;

    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database column transinfo.transdate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private String transdate;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.transId
     *
     * @return the value of transinfo.transId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getTransid() {
        return transid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.transId
     *
     * @param transid the value for transinfo.transId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setTransid(String transid) {
        this.transid = transid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.cardcode
     *
     * @return the value of transinfo.cardcode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.cardcode
     *
     * @param cardcode the value for transinfo.cardcode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.pId
     *
     * @return the value of transinfo.pId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.pId
     *
     * @param pid the value for transinfo.pId
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.GPRSCode
     *
     * @return the value of transinfo.GPRSCode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getGprscode() {
        return gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.GPRSCode
     *
     * @param gprscode the value for transinfo.GPRSCode
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setGprscode(String gprscode) {
        this.gprscode = gprscode;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.transtype
     *
     * @return the value of transinfo.transtype
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getTranstype() {
        return transtype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.transtype
     *
     * @param transtype the value for transinfo.transtype
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setTranstype(String transtype) {
        this.transtype = transtype;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.expenditure
     *
     * @return the value of transinfo.expenditure
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public BigDecimal getExpenditure() {
        return expenditure;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.expenditure
     *
     * @param expenditure the value for transinfo.expenditure
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setExpenditure(BigDecimal expenditure) {
        this.expenditure = expenditure;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.cardbalance
     *
     * @return the value of transinfo.cardbalance
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public BigDecimal getCardbalance() {
        return cardbalance;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.cardbalance
     *
     * @param cardbalance the value for transinfo.cardbalance
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setCardbalance(BigDecimal cardbalance) {
        this.cardbalance = cardbalance;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.version
     *
     * @return the value of transinfo.version
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.version
     *
     * @param version the value for transinfo.version
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method returns the value of the database column transinfo.transdate
     *
     * @return the value of transinfo.transdate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public String getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method sets the value of the database column transinfo.transdate
     *
     * @param transdate the value for transinfo.transdate
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setTransdate(String transdate) {
        this.transdate = transdate;
    }
}