package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Cardsync;
import com.pinelet.utp.entity.CardsyncExample;
import java.sql.SQLException;
import java.util.List;

public interface CardsyncDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int countByExample(CardsyncExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int deleteByExample(CardsyncExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int deleteByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    void insert(Cardsync record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    void insertSelective(Cardsync record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    List<Cardsync> selectByExample(CardsyncExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    List<Cardsync> selectByExamplePage(CardsyncExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    Cardsync selectByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int updateByExampleSelective(Cardsync record, CardsyncExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int updateByExample(Cardsync record, CardsyncExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int updateByPrimaryKeySelective(Cardsync record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    int updateByPrimaryKey(Cardsync record) throws SQLException;
}