package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Cardsync;
import com.pinelet.utp.entity.CardsyncExample;
import java.sql.SQLException;
import java.util.List;

public class CardsyncDAOImpl implements CardsyncDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public CardsyncDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int countByExample(CardsyncExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("cardsync.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int deleteByExample(CardsyncExample example) throws SQLException {
        int rows = sqlMapClient.delete("cardsync.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int deleteByPrimaryKey(String id) throws SQLException {
        Cardsync key = new Cardsync();
        key.setId(id);
        int rows = sqlMapClient.delete("cardsync.ibatorexgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void insert(Cardsync record) throws SQLException {
        sqlMapClient.insert("cardsync.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public void insertSelective(Cardsync record) throws SQLException {
        sqlMapClient.insert("cardsync.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Cardsync> selectByExample(CardsyncExample example) throws SQLException {
        List<Cardsync> list = sqlMapClient.queryForList("cardsync.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Cardsync> selectByExamplePage(CardsyncExample example, int start, int limit) throws SQLException {
        List<Cardsync> list = sqlMapClient.queryForList("cardsync.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public Cardsync selectByPrimaryKey(String id) throws SQLException {
        Cardsync key = new Cardsync();
        key.setId(id);
        Cardsync record = (Cardsync) sqlMapClient.queryForObject("cardsync.ibatorexgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int updateByExampleSelective(Cardsync record, CardsyncExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("cardsync.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int updateByExample(Cardsync record, CardsyncExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("cardsync.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int updateByPrimaryKeySelective(Cardsync record) throws SQLException {
        int rows = sqlMapClient.update("cardsync.ibatorexgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    public int updateByPrimaryKey(Cardsync record) throws SQLException {
        int rows = sqlMapClient.update("cardsync.ibatorexgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table cardsync
     *
     *  Tue Jun 25 17:08:31 CST 2013
     */
    private static class UpdateByExampleParms extends CardsyncExample {
        private Object record;

        public UpdateByExampleParms(Object record, CardsyncExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}