package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Cardinfo;
import com.pinelet.utp.entity.CardinfoExample;
import com.pinelet.utp.entity.CardinfoKey;
import java.sql.SQLException;
import java.util.List;

public interface CardinfoDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int countByExample(CardinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int deleteByExample(CardinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int deleteByPrimaryKey(CardinfoKey key) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    void insert(Cardinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    void insertSelective(Cardinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    List<Cardinfo> selectByExample(CardinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    List<Cardinfo> selectByExamplePage(CardinfoExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    Cardinfo selectByPrimaryKey(CardinfoKey key) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByExampleSelective(Cardinfo record, CardinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByExample(Cardinfo record, CardinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByPrimaryKeySelective(Cardinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByPrimaryKey(Cardinfo record) throws SQLException;
}