package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Cardinfo;
import com.pinelet.utp.entity.CardinfoExample;
import com.pinelet.utp.entity.CardinfoKey;
import java.sql.SQLException;
import java.util.List;

public class CardinfoDAOImpl implements CardinfoDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public CardinfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int countByExample(CardinfoExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("cardinfo.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int deleteByExample(CardinfoExample example) throws SQLException {
        int rows = sqlMapClient.delete("cardinfo.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int deleteByPrimaryKey(CardinfoKey key) throws SQLException {
        int rows = sqlMapClient.delete("cardinfo.ibatorexgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void insert(Cardinfo record) throws SQLException {
        sqlMapClient.insert("cardinfo.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void insertSelective(Cardinfo record) throws SQLException {
        sqlMapClient.insert("cardinfo.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Cardinfo> selectByExample(CardinfoExample example) throws SQLException {
        List<Cardinfo> list = sqlMapClient.queryForList("cardinfo.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Cardinfo> selectByExamplePage(CardinfoExample example, int start, int limit) throws SQLException {
        List<Cardinfo> list = sqlMapClient.queryForList("cardinfo.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public Cardinfo selectByPrimaryKey(CardinfoKey key) throws SQLException {
        Cardinfo record = (Cardinfo) sqlMapClient.queryForObject("cardinfo.ibatorexgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByExampleSelective(Cardinfo record, CardinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("cardinfo.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByExample(Cardinfo record, CardinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("cardinfo.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByPrimaryKeySelective(Cardinfo record) throws SQLException {
        int rows = sqlMapClient.update("cardinfo.ibatorexgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByPrimaryKey(Cardinfo record) throws SQLException {
        int rows = sqlMapClient.update("cardinfo.ibatorexgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table cardinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private static class UpdateByExampleParms extends CardinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, CardinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}