package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Commandinfo;
import com.pinelet.utp.entity.CommandinfoExample;
import java.sql.SQLException;
import java.util.List;

public interface CommandinfoDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int countByExample(CommandinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int deleteByExample(CommandinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int deleteByPrimaryKey(String commandid) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    void insert(Commandinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    void insertSelective(Commandinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    List<Commandinfo> selectByExample(CommandinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    List<Commandinfo> selectByExamplePage(CommandinfoExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    Commandinfo selectByPrimaryKey(String commandid) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int updateByExampleSelective(Commandinfo record, CommandinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int updateByExample(Commandinfo record, CommandinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int updateByPrimaryKeySelective(Commandinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table commandinfo
     *
     *  Sat Mar 30 15:41:48 CST 2013
     */
    int updateByPrimaryKey(Commandinfo record) throws SQLException;
}