package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Devicework;
import com.pinelet.utp.entity.DeviceworkExample;
import java.sql.SQLException;
import java.util.List;

public interface DeviceworkDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int countByExample(DeviceworkExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int deleteByExample(DeviceworkExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int deleteByPrimaryKey(String gprscode) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    void insert(Devicework record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    void insertSelective(Devicework record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    List<Devicework> selectByExample(DeviceworkExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    List<Devicework> selectByExamplePage(DeviceworkExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    Devicework selectByPrimaryKey(String gprscode) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int updateByExampleSelective(Devicework record, DeviceworkExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int updateByExample(Devicework record, DeviceworkExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int updateByPrimaryKeySelective(Devicework record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int updateByPrimaryKey(Devicework record) throws SQLException;
}