package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Deviceinfo;
import com.pinelet.utp.entity.DeviceinfoExample;
import java.sql.SQLException;
import java.util.List;

public interface DeviceinfoDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int countByExample(DeviceinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int deleteByExample(DeviceinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int deleteByPrimaryKey(String gprscode) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    void insert(Deviceinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    void insertSelective(Deviceinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    List<Deviceinfo> selectByExample(DeviceinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    List<Deviceinfo> selectByExamplePage(DeviceinfoExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    Deviceinfo selectByPrimaryKey(String gprscode) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int updateByExampleSelective(Deviceinfo record, DeviceinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int updateByExample(Deviceinfo record, DeviceinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int updateByPrimaryKeySelective(Deviceinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    int updateByPrimaryKey(Deviceinfo record) throws SQLException;
}