package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Deviceinfo;
import com.pinelet.utp.entity.DeviceinfoExample;
import java.sql.SQLException;
import java.util.List;

public class DeviceinfoDAOImpl implements DeviceinfoDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public DeviceinfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int countByExample(DeviceinfoExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("deviceinfo.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int deleteByExample(DeviceinfoExample example) throws SQLException {
        int rows = sqlMapClient.delete("deviceinfo.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int deleteByPrimaryKey(String gprscode) throws SQLException {
        Deviceinfo key = new Deviceinfo();
        key.setGprscode(gprscode);
        int rows = sqlMapClient.delete("deviceinfo.ibatorexgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public void insert(Deviceinfo record) throws SQLException {
        sqlMapClient.insert("deviceinfo.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public void insertSelective(Deviceinfo record) throws SQLException {
        sqlMapClient.insert("deviceinfo.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Deviceinfo> selectByExample(DeviceinfoExample example) throws SQLException {
        List<Deviceinfo> list = sqlMapClient.queryForList("deviceinfo.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Deviceinfo> selectByExamplePage(DeviceinfoExample example, int start, int limit) throws SQLException {
        List<Deviceinfo> list = sqlMapClient.queryForList("deviceinfo.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public Deviceinfo selectByPrimaryKey(String gprscode) throws SQLException {
        Deviceinfo key = new Deviceinfo();
        key.setGprscode(gprscode);
        Deviceinfo record = (Deviceinfo) sqlMapClient.queryForObject("deviceinfo.ibatorexgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int updateByExampleSelective(Deviceinfo record, DeviceinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("deviceinfo.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int updateByExample(Deviceinfo record, DeviceinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("deviceinfo.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int updateByPrimaryKeySelective(Deviceinfo record) throws SQLException {
        int rows = sqlMapClient.update("deviceinfo.ibatorexgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    public int updateByPrimaryKey(Deviceinfo record) throws SQLException {
        int rows = sqlMapClient.update("deviceinfo.ibatorexgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table deviceinfo
     *
     *  Fri Jan 18 17:24:02 CST 2013
     */
    private static class UpdateByExampleParms extends DeviceinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeviceinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}