package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Devicerecord;
import com.pinelet.utp.entity.DevicerecordExample;
import java.sql.SQLException;
import java.util.List;

public class DevicerecordDAOImpl implements DevicerecordDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public DevicerecordDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int countByExample(DevicerecordExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("devicerecord.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int deleteByExample(DevicerecordExample example) throws SQLException {
        int rows = sqlMapClient.delete("devicerecord.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void insert(Devicerecord record) throws SQLException {
        sqlMapClient.insert("devicerecord.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void insertSelective(Devicerecord record) throws SQLException {
        sqlMapClient.insert("devicerecord.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Devicerecord> selectByExample(DevicerecordExample example) throws SQLException {
        List<Devicerecord> list = sqlMapClient.queryForList("devicerecord.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Devicerecord> selectByExamplePage(DevicerecordExample example, int start, int limit) throws SQLException {
        List<Devicerecord> list = sqlMapClient.queryForList("devicerecord.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int updateByExampleSelective(Devicerecord record, DevicerecordExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("devicerecord.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int updateByExample(Devicerecord record, DevicerecordExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("devicerecord.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private static class UpdateByExampleParms extends DevicerecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, DevicerecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}