package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Devicework;
import com.pinelet.utp.entity.DeviceworkExample;
import java.sql.SQLException;
import java.util.List;

public class DeviceworkDAOImpl implements DeviceworkDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public DeviceworkDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int countByExample(DeviceworkExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("devicework.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int deleteByExample(DeviceworkExample example) throws SQLException {
        int rows = sqlMapClient.delete("devicework.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int deleteByPrimaryKey(String gprscode) throws SQLException {
        Devicework key = new Devicework();
        key.setGprscode(gprscode);
        int rows = sqlMapClient.delete("devicework.ibatorexgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void insert(Devicework record) throws SQLException {
        sqlMapClient.insert("devicework.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public void insertSelective(Devicework record) throws SQLException {
        sqlMapClient.insert("devicework.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Devicework> selectByExample(DeviceworkExample example) throws SQLException {
        List<Devicework> list = sqlMapClient.queryForList("devicework.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Devicework> selectByExamplePage(DeviceworkExample example, int start, int limit) throws SQLException {
        List<Devicework> list = sqlMapClient.queryForList("devicework.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public Devicework selectByPrimaryKey(String gprscode) throws SQLException {
        Devicework key = new Devicework();
        key.setGprscode(gprscode);
        Devicework record = (Devicework) sqlMapClient.queryForObject("devicework.ibatorexgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int updateByExampleSelective(Devicework record, DeviceworkExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("devicework.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int updateByExample(Devicework record, DeviceworkExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("devicework.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int updateByPrimaryKeySelective(Devicework record) throws SQLException {
        int rows = sqlMapClient.update("devicework.ibatorexgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    public int updateByPrimaryKey(Devicework record) throws SQLException {
        int rows = sqlMapClient.update("devicework.ibatorexgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table devicework
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    private static class UpdateByExampleParms extends DeviceworkExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeviceworkExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}