package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Devicerecord;
import com.pinelet.utp.entity.DevicerecordExample;
import java.sql.SQLException;
import java.util.List;

public interface DevicerecordDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int countByExample(DevicerecordExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int deleteByExample(DevicerecordExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    void insert(Devicerecord record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    void insertSelective(Devicerecord record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    List<Devicerecord> selectByExample(DevicerecordExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    List<Devicerecord> selectByExamplePage(DevicerecordExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int updateByExampleSelective(Devicerecord record, DevicerecordExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table devicerecord
     *
     *  Sun Mar 10 15:09:08 CST 2013
     */
    int updateByExample(Devicerecord record, DevicerecordExample example) throws SQLException;
}