package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Personalinfo;
import com.pinelet.utp.entity.PersonalinfoExample;
import java.sql.SQLException;
import java.util.List;

public class PersonalinfoDAOImpl implements PersonalinfoDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public PersonalinfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int countByExample(PersonalinfoExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("personalinfo.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int deleteByExample(PersonalinfoExample example) throws SQLException {
        int rows = sqlMapClient.delete("personalinfo.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int deleteByPrimaryKey(String pid) throws SQLException {
        Personalinfo key = new Personalinfo();
        key.setPid(pid);
        int rows = sqlMapClient.delete("personalinfo.ibatorexgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void insert(Personalinfo record) throws SQLException {
        sqlMapClient.insert("personalinfo.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public void insertSelective(Personalinfo record) throws SQLException {
        sqlMapClient.insert("personalinfo.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Personalinfo> selectByExample(PersonalinfoExample example) throws SQLException {
        List<Personalinfo> list = sqlMapClient.queryForList("personalinfo.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Personalinfo> selectByExamplePage(PersonalinfoExample example, int start, int limit) throws SQLException {
        List<Personalinfo> list = sqlMapClient.queryForList("personalinfo.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public Personalinfo selectByPrimaryKey(String pid) throws SQLException {
        Personalinfo key = new Personalinfo();
        key.setPid(pid);
        Personalinfo record = (Personalinfo) sqlMapClient.queryForObject("personalinfo.ibatorexgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int updateByExampleSelective(Personalinfo record, PersonalinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("personalinfo.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int updateByExample(Personalinfo record, PersonalinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("personalinfo.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int updateByPrimaryKeySelective(Personalinfo record) throws SQLException {
        int rows = sqlMapClient.update("personalinfo.ibatorexgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    public int updateByPrimaryKey(Personalinfo record) throws SQLException {
        int rows = sqlMapClient.update("personalinfo.ibatorexgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table personalinfo
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    private static class UpdateByExampleParms extends PersonalinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, PersonalinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}