package com.pinelet.utp.dao;

import com.pinelet.utp.entity.PersonrelExample;
import com.pinelet.utp.entity.PersonrelKey;
import java.sql.SQLException;
import java.util.List;

public interface PersonrelDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    int countByExample(PersonrelExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    int deleteByExample(PersonrelExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    int deleteByPrimaryKey(PersonrelKey key) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    void insert(PersonrelKey record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    void insertSelective(PersonrelKey record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    List<PersonrelKey> selectByExample(PersonrelExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    List<PersonrelKey> selectByExamplePage(PersonrelExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    int updateByExampleSelective(PersonrelKey record, PersonrelExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table personrel
     *
     *  Sun Jan 13 16:31:41 CST 2013
     */
    int updateByExample(PersonrelKey record, PersonrelExample example) throws SQLException;
}