package com.pinelet.utp.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pinelet.utp.entity.Transinfo;
import com.pinelet.utp.entity.TransinfoExample;
import java.sql.SQLException;
import java.util.List;

public class TransinfoDAOImpl implements TransinfoDAO {
    /**
     * This field was generated by CreditEase ibator-extending.
     * This field corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public TransinfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int countByExample(TransinfoExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("transinfo.ibatorexgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int deleteByExample(TransinfoExample example) throws SQLException {
        int rows = sqlMapClient.delete("transinfo.ibatorexgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int deleteByPrimaryKey(String transid) throws SQLException {
        Transinfo key = new Transinfo();
        key.setTransid(transid);
        int rows = sqlMapClient.delete("transinfo.ibatorexgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void insert(Transinfo record) throws SQLException {
        sqlMapClient.insert("transinfo.ibatorexgenerated_insert", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public void insertSelective(Transinfo record) throws SQLException {
        sqlMapClient.insert("transinfo.ibatorexgenerated_insertSelective", record);
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Transinfo> selectByExample(TransinfoExample example) throws SQLException {
        List<Transinfo> list = sqlMapClient.queryForList("transinfo.ibatorexgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Transinfo> selectByExamplePage(TransinfoExample example, int start, int limit) throws SQLException {
        List<Transinfo> list = sqlMapClient.queryForList("transinfo.ibatorexgenerated_selectByExample", example, start, limit);
        return list;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public Transinfo selectByPrimaryKey(String transid) throws SQLException {
        Transinfo key = new Transinfo();
        key.setTransid(transid);
        Transinfo record = (Transinfo) sqlMapClient.queryForObject("transinfo.ibatorexgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByExampleSelective(Transinfo record, TransinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("transinfo.ibatorexgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByExample(Transinfo record, TransinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("transinfo.ibatorexgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByPrimaryKeySelective(Transinfo record) throws SQLException {
        int rows = sqlMapClient.update("transinfo.ibatorexgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    public int updateByPrimaryKey(Transinfo record) throws SQLException {
        int rows = sqlMapClient.update("transinfo.ibatorexgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by CreditEase ibator-extending.
     * This class corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    private static class UpdateByExampleParms extends TransinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, TransinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}