package com.pinelet.utp.dao;

import com.pinelet.utp.entity.Transinfo;
import com.pinelet.utp.entity.TransinfoExample;
import java.sql.SQLException;
import java.util.List;

public interface TransinfoDAO extends UTPDAO {
    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int countByExample(TransinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int deleteByExample(TransinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int deleteByPrimaryKey(String transid) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    void insert(Transinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    void insertSelective(Transinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    List<Transinfo> selectByExample(TransinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    List<Transinfo> selectByExamplePage(TransinfoExample example, int start, int limit) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    Transinfo selectByPrimaryKey(String transid) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByExampleSelective(Transinfo record, TransinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByExample(Transinfo record, TransinfoExample example) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByPrimaryKeySelective(Transinfo record) throws SQLException;

    /**
     * This method was generated by CreditEase ibator-extending.
     * This method corresponds to the database table transinfo
     *
     *  Mon Mar 04 18:34:57 CST 2013
     */
    int updateByPrimaryKey(Transinfo record) throws SQLException;
}